### PR TITLE
Add Python methods to hashtable so it can be used like a dict

### PR DESCRIPTION
**Pull request by geographika**
Supersedes #5614

Add various Python methods so that a hashtable can be used like a dict. See #5582 for background. 
API is now as follows:

```python
import mapscript
ht = mapscript.hashTableObj()

ht["key1"] = "value1"
ht["key2"] = "value2"
ht["key3"] = "value3"
ht["key4"] = "value4"

del ht["key1"]
print(ht.keys)
print(len(ht))
print("k1" in ht)
print(len(ht))
```

Or for a more concrete example:

```python

print(map.web.metadata.keys()) # ['wms_srs', 'ows_enable_request', 'ows_http_max_age']
print(map.web.metadata["wms_srs"]) # EPSG:4326
map.web.metadata["wms_srs"] = "EPSG:2157"
print(map.web.metadata["wms_srs"])  # EPSG:2157
```

### CODE REVIEW

**Comment by geographika** [comment]
Is this likely to make the 7.2 cut? If not I can recreate the pull request against master. 

The functionality is tested by both mapscript/python/tests/cases/hashtest.py and msautotest/mspython/test_mapio.py

Currently the hashtable implementation in Python Mapscript doesn't match the docs, or allow setting of values.

**Comment by sdlime** [comment]
Yes, I think this can be merged. Can you do it?
________________________________

**Comment by geographika** [comment]
@sdlime - I don't have commit rights so can't help there sorry!

@rouault wrote the original SWIG typemap so could have reservations, although the new approach has the same API  as the test_mapio.py that was written to test they typemap so should be ok.

**Comment by sdlime** [comment]
Probably should wait on a blessing from @rouault before pulling the trigger then.

**Comment by rouault** [comment]
@geographika @sdlime Sorry, I missed your previous pings. Too many notifications from too many repositories.. Squashed and merged

**Comment by geographika** [comment]
@rouault - thanks for merging!

**Pull request merged**
