### PR TITLE
No need of msWrapText according to issue #5609

### PR DESCRIPTION
**Pull request by SunveerSingh**
After going through the code and following the issue #5609 I found that the function msWrapText is not used anywhere, so please let me know if it is correct!

### CODE REVIEW

**Comment by geographika** [comment]
@SunveerSingh - you will probably want to make this pull request against the `master `branch rather than `mapserver:branch-7-0`. This explains why Travis and Appveyor are both currently failing.

**Comment by SunveerSingh** [comment]
I have changed the branch to master.

**Comment by geographika** [comment]
@SunveerSingh - to trigger the Travis and Appveyor builds again could you try closing and reopening the pull request to see if all the checks pass?

**Comment by SunveerSingh** [comment]
@geographika this time travis is failing, what should I do to fix it?

**Comment by geographika** [comment]
@SunveerSingh - I retriggered the Travis build. It looked like there was a network problem previously unrelated to the pull request. Both CI tests are now passing.

**Comment by SunveerSingh** [comment]
@geographika Thank You, can you merge it now?

**Comment by geographika** [comment]
@SunveerSingh - I've looked through the codebase and there are indeed no longer and other references to this function. 
One thing to fix before merging is to also delete the associated comment, as this is also now redundant:

```
/**
 * replace wrap characters with \n , respecting maximal line length.
 *
 * returns a pointer to the newly allocated text. memory is controlled
 * inside this function, so the caller MUST use the pointer returned by
 * the function:
 * text = msWrapText(label,text);
 *
 * TODO/FIXME: function will produce erroneous/crashing? results
 * if the wrap character is encoded with multiple bytes
 *
 * see http://mapserver.org/development/rfc/ms-rfc-40.html
 * for a summary of how wrap/maxlength interact on the result
 * of the text transformation
 */
```

**Comment by SunveerSingh** [comment]
@geographika Done

**Comment by SunveerSingh** [comment]
@geographika tests passed can we merge it?

**Comment by geographika** [comment]
Thanks @SunveerSingh !

**Pull request merged**
