### PR TITLE
Styling - Fixes alpha value for hex colors

### PR DESCRIPTION
**Pull request by ravhed**
Fixes issue #5882. The issue was introduced by the following commit:

https://github.com/mapserver/mapserver/commit/4fbd7aee1fa2864bf320e9756296b0912774afeb

This commit changes back to the old behavior so that opacity is only
applied if the style have any bindings. A test case to test this
has also been added.

### CODE REVIEW

**Comment by ravhed** [comment]
It seems like some SLD tests fail. I will have to investigate those

**Comment by jbo-ads** [comment]
Looks like I am the one who introduced that regression. I'll take a look at SLD tests.

**Comment by jbo-ads** [comment]
I just submitted changes in SLD tests to ravhed:hex-opacity branch, see ravhed#1.

**Comment by ravhed** [comment]
> I just submitted changes in SLD tests to ravhed:hex-opacity branch, see [ravhed#1](https://github.com/ravhed/mapserver/pull/1).

Thanks a lot for your help! I haven't had time to look at the tests myself

**Comment by jmckenna** [comment]
@jbo-ads would this bug also affect branch-7-6 code?  Just wondering the impact.

**Comment by jbo-ads** [comment]
@jmckenna Yes, the bug was present since my first SLD changes.

**Comment by jmckenna** [comment]
ok thanks @jbo-ads

**Comment by rouault** [comment]
@jbo-abs I let you issue a backport PR to 7.6 branch

**Comment by jmckenna** [comment]
cherry-picked into branch-7-6

**Pull request merged**
