### PR TITLE
Implement RFC-113 Layer Compositing Framework

### PR DESCRIPTION
**Pull request by tbonfort**
http://mapserver.org/development/rfc/ms-rfc-113.html

### CODE REVIEW

**Comment by tbonfort** [comment]
merged into master in 29db335

**Comment by rouault** [comment]
What is the minimum cairo version required ?
I get build failures with the ancient cairo 1.8.10-2ubuntu1 of my ancient Ubuntu 10.04:
```/home/even/mapserver/git/mapserver/mapcairo.c:809: error: ‘CAIRO_OPERATOR_MULTIPLY’ undeclared (first use in this function)
/home/even/mapserver/git/mapserver/mapcairo.c:809: error: (Each undeclared identifier is reported only once
/home/even/mapserver/git/mapserver/mapcairo.c:809: error: for each function it appears in.)
/home/even/mapserver/git/mapserver/mapcairo.c:811: error: ‘CAIRO_OPERATOR_SCREEN’ undeclared (first use in this function)
/home/even/mapserver/git/mapserver/mapcairo.c:813: error: ‘CAIRO_OPERATOR_OVERLAY’ undeclared (first use in this function)
/home/even/mapserver/git/mapserver/mapcairo.c:815: error: ‘CAIRO_OPERATOR_DARKEN’ undeclared (first use in this function)
/home/even/mapserver/git/mapserver/mapcairo.c:817: error: ‘CAIRO_OPERATOR_LIGHTEN’ undeclared (first use in this function)
/home/even/mapserver/git/mapserver/mapcairo.c:819: error: ‘CAIRO_OPERATOR_COLOR_DODGE’ undeclared (first use in this function)
/home/even/mapserver/git/mapserver/mapcairo.c:821: error: ‘CAIRO_OPERATOR_COLOR_BURN’ undeclared (first use in this function)
/home/even/mapserver/git/mapserver/mapcairo.c:823: error: ‘CAIRO_OPERATOR_HARD_LIGHT’ undeclared (first use in this function)
/home/even/mapserver/git/mapserver/mapcairo.c:825: error: ‘CAIRO_OPERATOR_SOFT_LIGHT’ undeclared (first use in this function)
/home/even/mapserver/git/mapserver/mapcairo.c:827: error: ‘CAIRO_OPERATOR_DIFFERENCE’ undeclared (first use in this function)
/home/even/mapserver/git/mapserver/mapcairo.c:829: error: ‘CAIRO_OPERATOR_EXCLUSION’ undeclared (first use in this function)
/

```

**Comment by rouault** [comment]
Answer to myself: it seems that cairo 1.10 is required

**Comment by tbonfort** [comment]
I think they were renamed. I'll have a look and commit an #ifdef'd block if that's possible.

**Comment by rouault** [comment]
There are also a few warnings possibly related with that dev :

Extract:
```
/home/even/mapserver/git/mapserver/mapcontext.c: In function ‘msLoadMapContextLayer’:
/home/even/mapserver/git/mapserver/mapcontext.c:1037: warning: implicit declaration of function ‘initLayerCompositer’

[ 26%] Building C object CMakeFiles/mapserver.dir/mapcopy.c.o
/home/even/mapserver/git/mapserver/mapcopy.c: In function ‘msCopyLabel’:
/home/even/mapserver/git/mapserver/mapcopy.c:403: warning: implicit declaration of function ‘initLeader’
/home/even/mapserver/git/mapserver/mapcopy.c: In function ‘msCopyLayer’:
/home/even/mapserver/git/mapserver/mapcopy.c:1115: warning: implicit declaration of function ‘freeGrid’

Building C object CMakeFiles/mapserver.dir/maputil.c.o
/home/even/mapserver/git/mapserver/maputil.c: In function ‘msCheckParentPointer’:
/home/even/mapserver/git/mapserver/maputil.c:2164: warning: unused variable ‘fmt’
/home/even/mapserver/git/mapserver/maputil.c: In function ‘msSetLayerOpacity’:
/home/even/mapserver/git/mapserver/maputil.c:2621: warning: implicit declaration of function ‘initLayerCompositer’
/home/even/mapserver/git/mapserver/maputil.c:2624: warning: control reaches end of non-void function

[ 61%] /home/even/mapserver/git/mapserver/mapagg.cpp: In function ‘int aggCompositeRasterBuffer(imageObj*, rasterBufferObj*, CompositingOperation, int)’:
/home/even/mapserver/git/mapserver/mapagg.cpp:1321: warning: comparison between ‘enum CompositingOperation’ and ‘enum mapserver::comp_op_e’
```

**Pull request closed without merging**
