### PR TITLE
WIP: remove PHP-native MapScript code for 8.0 release

### PR DESCRIPTION
**Pull request by jmckenna**
- part of the MapServer 8.0 release plan (https://github.com/MapServer/MapServer/wiki/MapServer-8.0-Release-Plan)
- as PHP-native MapScript is unmaintained and now causing constant security concerns & efforts
- as PHP 7 & 8 are now well supported by SWIG
  - see issue #6201 for PHP 8.0 progress with SWIG MapScript
- this pull request:
  - removes old native PHP MapScript
  - updates TravisCI and GitHub build action to use Ubuntu Focal
  - builds PHPNG MapScript for PHP 7.4.6, 8.0.19, 8.1.6
  - builds Python MapScript for Python 3.7.7, 3.8.3, 3.9.0
  - updates many msautotest tests
  - updates all PHP unit tests

### CODE REVIEW

**Comment by rouault** [comment]
Just letting a note that I was considering updating the Vagrant scripts to be consistent with the new ubuntu:20.04 baseline which should help updating the latest expected results, in case someone had already started looking at that

**Comment by rouault** [comment]
@jmckenna I see that ubuntugis has updated the GDAL version to 3.4.3 which explains the need to regenerate some files. Regarding the remaining last failures, do I understand correctly from your commit comment you've run the Docker recipee to update the files ? I could give it another try if you wish (I remember some oddity during my previous commits where some generated TIFF files were not binary identical between Docker and Vagrant also using the same GDAL version)

**Comment by jmckenna** [comment]
@rouault yes I've run this through Docker (as I am battling the latest UbuntuGIS changes as you mentioned), and those last 4 'alternative' files committed are from the Docker container...I was examining why those 4 alternative files aren't being accepted (I see that they should pass using this `.alternative` extension, through line 88 of testlib.py.   I'm not sure your question exactly, but yes I am currently updating all of this to match the latest UbuntuGIS changes.  Did I answer your question?  Sorry, ha, I'm deep into this, my words aren't making sense here :)

**Comment by jmckenna** [comment]
@rouault as you wrote this, I was exactly comparing the binary NetCDF files, as to why those 4 alternative files aren't passing.....   does this follow what you were asking?  I think what you suggested is exactly what I am doing.  Am I on the correct track?

**Comment by jmckenna** [comment]
> 
> yes, thanks. Your approach looks good. Just let me know if you need a second look/try on this. (Up to now, the Docker approach was convenient to be able to locally reproduce. Contrary to Travis-CI which has preinstalled components not always easy to reproduce)

ah good, thanks, deal.

**Comment by rouault** [comment]
https://github.com/jmckenna/MapServer/pull/3 solves the issue with the .nc test files (the build now fail later on the PHP tests)

**Comment by jmckenna** [comment]
> [jmckenna#3](https://github.com/jmckenna/MapServer/pull/3) solves the issue with the .nc test files (the build now fail later on the PHP tests)

ah thanks!!!

**Comment by jmckenna** [comment]
thanks for everyone's help through this.  Merging (for the beta this coming Friday!)

**Pull request merged**
