### PR TITLE
Fix opacity calculation problem with the agg renderer (#5697)

### PR DESCRIPTION
**Pull request by szekerest**

### CODE REVIEW

**Comment by szekerest** [comment]
@jmckenna @rouault I wonder how to recreate the expected files for the failed tests. I created an ubuntu VM, and run msautotest, but most of the generated files are binary different than the files from the expected directories.

**Comment by rouault** [comment]
> I created an ubuntu VM, and run msautotest, but most of the generated files are binary different than the files from the expected directories.

you need a 20.04 one to get the "right" version of the libraries. As I've it handy, I've just checkout your branch and pushed the updated expected results

**Comment by szekerest** [comment]
> > I created an ubuntu VM, and run msautotest, but most of the generated files are binary different than the files from the expected directories.
> 
> you need a 20.04 one to get the "right" version of the libraries. As I've it handy, I've just checkout your branch and pushed the updated expected results

Great, thanks @rouault 
I'll give it a try creating a 20.04 VM. I wonder if we could add that requirement into the msautotests docs for further reference.

**Comment by rouault** [comment]
backport done in https://github.com/MapServer/MapServer/pull/7087

**Comment by geographika** [comment]
@szekerest @rouault - the [vagrant](https://mapserver.org/development/tests/vagrant.html) approach works well for me to get the exact binary outputs on a Windows machine. Isn't this the recommended approach?

**Comment by rouault** [comment]
> Isn't this the recommended approach?

yes, that can be convenient .Added to https://github.com/MapServer/MapServer/pull/7086

**Pull request merged**
