### PR TITLE
Add Kitware's APT repository to get recent CMake in Vagrant build

### PR DESCRIPTION
**Pull request by jbo-ads**
This fixes issue #6154 about failure on Vagrant build.

### CODE REVIEW

**Comment by geographika** [comment]
Thanks @jbo-ads. 
It seems the Travis Bionic build has CMake 3.12 (released in 2018) by [default](https://docs.travis-ci.com/user/reference/bionic#compilers-and-build-toolchain). I was wondering why the Bionic VM used an older version. 
Hopefully this addition can be removed in the future when 3.12 becomes available on standard channels. 

@szekerest - probably same issue for GISInternals builds. Appveyor has a [minimum version of 3.12](https://www.appveyor.com/docs/windows-images-software/#tools).

**Comment by jmckenna** [comment]
@jbo-ads is this related to the failing msautotest for this build? (it is failing on /msautotest/wxs/wms_client_111.map on Travis) Can you take a look?

**Comment by jbo-ads** [comment]
I can't image a way they are related: My fix concerns Vagrant and as far as I know it is not triggered by Travis build.

**Comment by rouault** [comment]
> (it is failing on /msautotest/wxs/wms_client_111.map on Travis) Can you take a look?

absolutely not related. It is an issue with a request to http://demo.mapserver.org/cgi-bin/wms? that failed randomly

**Comment by jmckenna** [comment]
I thought so too.  I didn't merge this because of that issue though.  I'll try to re-trigger the build now...thanks @jbo-ads

**Comment by jmckenna** [comment]
build has been re-triggered.  thanks @jbo-ads and @rouault

**Comment by jmckenna** [comment]
It seems to be a problem with Travis connectivity.   Sorry for the noise.

**Pull request merged**
