### PR TITLE
[msautotest] add FlatGeobuf WFS tests

### PR DESCRIPTION
**Pull request by jmckenna**
- related to changes in #6553
- cc @bjornharrtell

### CODE REVIEW

**Comment by jmckenna** [comment]
@bjornharrtell I need your help to debug this.  It gives a memory leak error (see bottom of https://app.travis-ci.com/github/MapServer/MapServer/jobs/576030002 ).

**Comment by rouault** [comment]
https://github.com/jmckenna/MapServer/pull/4 should fix the memory leak, and a potential other issue with column mapping (I believe @landryb or maybe someone else mentionned that he couldn't get the value of some columns)

**Comment by jmckenna** [comment]
great thanks for this @rouault !

**Comment by bjornharrtell** [comment]
Much appreciated @rouault!

**Pull request merged**
