### PR TITLE
PostGIS: fix ST_Intersects() with collections with PostGIS < 2.5.

### PR DESCRIPTION
**Pull request by rouault**
Fixes https://github.com/MapServer/MapServer/pull/6355#issuecomment-877290417

CC @sdlime

### CODE REVIEW

**Comment by jmckenna** [comment]
Thanks @rouault.  @sdlime could you test this?  (will include in 7.6.4)

**Comment by rouault** [comment]
I'm taking care of the backport

**Comment by jmckenna** [comment]
@rouault thanks, I was looking at the code, thanks for tackling.

**Comment by sdlime** [comment]
I can test when this hits branch-7-6...

**Pull request merged**
