### PR TITLE
Fix white-space handling on mappostgis.c

### PR DESCRIPTION
**Pull request by tlaczy**
Fix white-space handling on function msPostGISParseData.
The DATA field contains " from\n" or similar generate invalid SQL, because '\n' don't handled as white-space

### CODE REVIEW

**Comment by jmckenna** [comment]
thanks @tlaczy nice change for PostGIS users!

**Comment by sbrunner** [comment]
I suspect that from the merge I get the error 
```
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows/1.1" version="2.0.0" xml:lang="en-US" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd">
  <ows:Exception exceptionCode="NoApplicableCode" locator="mapserv">
    <ows:ExceptionText>msPostGISParseData(): Query error. Error parsing PostGIS DATA variable.  You must specify 'using unique' when supplying a subselect in the data definition.</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```
For the DATA:
```
DATA "geom FROM (SELECT * FROM polygons) AS foo USING UNIQUE name USING srid=4326"
```
:-/

**Comment by jmckenna** [comment]
Does anyone have a small test case handy?  (I have PostGIS 3 and PG 12.1 locally to test)  @tlaczy @sbrunner ?

**Comment by jmckenna** [comment]
I'll try using @sbrunner 's connection above.

**Comment by jmckenna** [comment]
@sbrunner I cannot reproduce your issue locally (PostgreSQL 12,2, PostGIS 3.0.1).  Can you please create a small test case and attach it here, to reproduce?

**Comment by tlaczy** [comment]
Greetings to everyone!
I checked my changes again. I didn't find a bug in it.
I did not test it directly because I do not have an executable binary for the current, patched state of 'mapserver' master brand.
Can I download the executable code somewhere? Like Travis, for example?
Thanks

**Comment by sbrunner** [comment]
Sorry, for long time to responds, I was on holiday :-)
I just get the Capabilities with this file: https://github.com/camptocamp/docker-mapserver/blob/master/acceptance_tests/config/mapserver/mapserver.map.tmpl

**Comment by jmckenna** [comment]
Thanks for pointing to that @sbrunner 

I have tested your mapfile with today's master build (with PostgreSQL 12.2, PostGIS 3.0.1).  The only change that I had to make to your mapfile was to set an image SIZE parameter. Here was my command:
```
shp2img -m mapserver.map -o ttt.png -all_debug 5
```
And the result is valid, with no errors:
```
msLoadMap(): 0.008s
msDrawMap(): rendering using outputformat named jpeg (AGG/JPEG).
msDrawMap(): WMS/WFS set-up and query, 0.000s
msPostGISLayerOpen called: geom FROM (SELECT * FROM polygons) AS foo USING UNIQUE name USING srid=4326
msPostGISLayerOpen: No connection in pool, creating a fresh one.
msConnPoolRegister(polygons,user=postgres password=postgres dbname=camptocamptest host=localhost port=5436,00EF29B0)
msPostGISLayerOpen: Got PostGIS version 30000.
msPostGISLayerOpen: Forcing 2D geometries: no.
msPostGISLayerFreeItemInfo called.
msPostGISLayerWhichShapes called.
msPostGISParseData called.
msPostGISParseData: unique_column=name, srid=4326, geom_column_name=geom, table_name=(SELECT * FROM polygons) AS foo
msPostGISBuildSQL called.
msPostGISBuildSQLItems called.
msPostGISBuildSQLItems: 0 items requested.
msPostGISBuildSQLFrom called.
msPostGISBuildSQLWhere called.
msPostGISBuildSQLSRID called.
msPostGISBuildSQLSRID: SRID provided (4326)
msPostGISBuildSQLBox called.
msPostGISLayerWhichShapes query: select ST_AsBinary(("geom"),'NDR') as geom,"name"::text from (SELECT * FROM polygons) AS foo where "geom" && ST_GeomFromText('POLYGON((-180 -119.899833055092,-180 119.899833055092,180 119.899833055092,180 -119.899833055092,-180 -119.899833055092))',4326)
msPostGISLayerWhichShapes query status: PGRES_TUPLES_OK (2)
msPostGISLayerWhichShapes got 1 records in result.
msPostGISLayerNextShape called.
msPostGISReadShape called.
msPostGISReadShape: Setting shape->index = 0
msPostGISReadShape: Setting shape->resultindex = 0
msPostGISReadShape: [index] 0
msPostGISReadShape: [shape] POLYGON ((-50.0000000000000000 -50.0000000000000000, 50.0000000000000000 -50.0000000000000000, 50.0000000000000000 50.0000000000000000, -50.0000000000000000 -50.0000000000000000))
msPostGISLayerNextShape called.
msPostGISLayerFreeItemInfo called.
msPostGISLayerClose called: geom FROM (SELECT * FROM polygons) AS foo USING UNIQUE name USING srid=4326
msConnPoolRelease(polygons,user=postgres password=postgres dbname=camptocamptest host=localhost port=5436,00EF29B0)
msDrawMap(): Layer 0 (polygons), 0.301s
msDrawMap(): Drawing Label Cache, 0.000s
msDrawMap() total time: 0.333s
msSaveImage(ttt.png) total time: 0.075s
msFreeMap(): freeing map at 00E58EB0.
freeLayer(): freeing layer at 00EC04F0.
msPostGISLayerIsOpen called.
shp2img total time: 0.425s
msConnPoolClose(user=postgres password=postgres dbname=camptocamptest host=localhost port=5436,00EF29B0)
```
ttt

**Comment by sbrunner** [comment]
It seems that's your tight :-/, many thanks :-)

**Pull request merged**
