### PR TITLE
Issue #5796 - Latest OCI library files not found

### PR DESCRIPTION
**Pull request by bmulcahy**
Added version specific libnnz name to the ORACLE_NNZ_NAMES list

### CODE REVIEW

**Comment by jmckenna** [comment]
thanks @bmulcahy !

**Comment by sdlime** [comment]
Should this have been against master instead with a 7.4 backport?

**Comment by jmckenna** [comment]
yes likely, i noticed that also.

**Comment by bmulcahy** [comment]
Would you like me to create a new pull request?

**Comment by sdlime** [comment]
Nah... We'll just need to merge the 7.4 branch with master. My comment was more for future reference since we recently changed our typical target branch to master. No worries!

**Comment by jmckenna** [comment]
Merged into master.

**Pull request merged**
