### PR TITLE
WMS Client - Crash when WMS client request is one pixel in width or height

### PR DESCRIPTION
**Pull request by ravhed**
See #5815 for details.

### CODE REVIEW

**Comment by ravhed** [comment]
It seems like this change didn't pass one of the WMS client tests. This pull request should not be merged until I've pushed a fix for it.

**Comment by sdlime** [comment]
I suppose we need to fix the regression created by #5707 first...

**Comment by ravhed** [comment]
I've updated the remaining tests now. I believe the appveyor build failure is not related to my changes.

**Comment by jmckenna** [comment]
thanks @ravhed !

**Pull request merged**
