### PR TITLE
MINSCALE and MAXSCALE are both deprecated

### PR DESCRIPTION
**Pull request by geographika**
Update to MAXSCALEDENOM in test case

### CODE REVIEW

**Comment by rouault** [comment]
I'm wondering if it doesn't make sense to still have them tested ? They are deprecated, but are still supposed to work, so better make sure they still work with the test (although I don't think anyone really madesure that deprecated keywords are still tested...)

**Comment by geographika** [comment]
@rouault - there are plenty of deprecated keywords around still, the reason I added this particular case was because MINSCALE and MAXSCALE are no longer listed in the CLASS docs page - http://mapserver.org/mapfile/class.html

The pull request can be closed until further discussion on the dev lists if that is appropriate?

I'm not too far off allowing deprecated keywords to be highlighted in a mapfile with Python, so will post this to the dev list when it's ready.

**Comment by rouault** [comment]
Actually I see there are a lot of remaining MAXSCALE uses: https://github.com/mapserver/mapserver/search?utf8=%E2%9C%93&q=%22MAXSCALE%22&type=

@sdlime Any opinion if we should remove all uses of deprecated keywords in msautotest, or keep some on purpose to check that we still work with those ? I raised this point, but I'm not at all strong about that. I don't maintain old mapfiles ;-)

**Comment by jmckenna** [comment]
thanks @geographika Merging as you recommended, and further discussion can happen on -dev as you suggested.

**Pull request merged**
