### PR TITLE
Fixes for several security vulnerabilities found with libFuzzer

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Comment by rouault** [comment]
Please redo your pull request against the master branch.
Which setup (scripts, etc.) did you use to find this ?

**Comment by MaxKellermann** [comment]
Changed to branch "main".
I started writing various fuzzers for a https://github.com/XCSoar/XCSoar/ which is a navigation app for pilots. It uses part of the MapServer code to load shape files. (Patched to be able to load it from ZIP files.)
This is the fuzzer: https://github.com/XCSoar/XCSoar/blob/master/fuzzer/src/FuzzTopographyFile.cpp ... which however talks to XCSoar's C++ code, which deep inside calls into MapServer's C code. So this fuzzer may not be useful for you.

**Comment by jmckenna** [comment]
thanks for this effort @MaxKellermann !

**Comment by rouault** [comment]
@jmckenna Do you want me to create an issue about the backport bot no longer working ?
I'll do a manual backport of this PR

**Comment by jmckenna** [comment]
@rouault I was just working on it, fix coming...

**Pull request merged**
