### PR TITLE
Addresses open file handles when parse errors occur in include files  (Issue #5942)

### PR DESCRIPTION
**Pull request by sdlime**

### CODE REVIEW

**Comment by rouault** [comment]
An addition in msautotest might be useful

**Comment by sdlime** [comment]
A specific test would need to take the form of something that would show the number of open file handles after a process closed. I'm not sure how that would be done or how it could be included in the test suite.

**Comment by rouault** [comment]
> A specific test would need to take the form of something that would show the number of open file handles after a process closed

I had presumed that the CI config that runs with Address Sanitizer enabled (PHP_7.2_WITH_ASAN) would warn about unclosed files as a memory leak, but on a small test case, I see this isn't the case unfortunately. Valgrind can see this with --leak-check=full --show-leak-kinds=all however
```
==27735== 552 bytes in 1 blocks are still reachable in loss record 1 of 1
==27735==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27735==    by 0x4EA7CDC: __fopen_internal (iofopen.c:69)
==27735==    by 0x40053C: main (leak.c:4)
```
However I think there's still a merit in having such a test case: at least this makes sure that the error code paths are hit and don't cause crash (I'm sure they don't now :-), but it might if someone later touches it)

**Comment by sdlime** [comment]
I can certainly create a couple of scenarios that generate parse errors 0, 1 and 2 includes deep.

**Comment by sdlime** [comment]
Bump, @dmorissette or @alexbrault, do you have time to test this fix? --Steve

**Comment by jmckenna** [comment]
No response on testing, but am merging this now...

**Pull request merged**
