### PR TITLE
Cutting things too close when offsetting a label from a marker. Apply…

### PR DESCRIPTION
**Pull request by sdlime**
… MARKER_SLOP to UL, UR, LR, LL positions too. (#5436)

### CODE REVIEW

**Comment by sdlime** [comment]
Note the end affect is a nudging of labels in the UL/UR/LL/LR positions away from the label point. Doesn't surprise me that some tests failed. Will check on them... --Steve

**Comment by jmckenna** [comment]
@sdlime did you mean to merge this branch-7-0 ?    (should this delay the 7.0.6 release?)

**Comment by jmckenna** [comment]
tagging 7.0.6 now....

**Comment by jmckenna** [comment]
@sdlime did you mean to push this to the branch-7-0 ?

**Comment by jmckenna** [comment]
@sdlime can you take a look at this and rebase it against master if possible (instead of branch-6-4) ?

**Comment by rouault** [comment]
That patch had been applied to master in d069dbd71

**Pull request closed without merging**
