### PR TITLE
Labeling lines with zero lengths may cause the application to crash (#6493)

### PR DESCRIPTION
**Pull request by szekerest**

### CODE REVIEW

**Comment by sdlime** [comment]
It's not clear to me what these changes prevent downstream. What am I missing?

**Comment by szekerest** [comment]
@sdlime These changes causes to initialize the values (longest_segment_index, longest_segment_line_index, longest_segment_point_index, longest_line_index) even if the line length is zero.

**Comment by sdlime** [comment]
I saw that but I couldn't tell why that fixes anything.

**Comment by szekerest** [comment]
Because, the following code in (msLineLabelPoint) will use uninitialized longest_segment_index as soon as the line length is zero.

```
        j = ll->longest_segment_index;
        lar->label_points[lar->num_label_points].x = (p->point[j-1].x + p->point[j].x)/2.0;
        lar->label_points[lar->num_label_points].y = (p->point[j-1].y + p->point[j].y)/2.0;
```

**Comment by sdlime** [comment]
> Because, the following code in (msLineLabelPoint) will use uninitialized longest_segment_index as soon as the line length is zero.
> 
> ```
>         j = ll->longest_segment_index;
>         lar->label_points[lar->num_label_points].x = (p->point[j-1].x + p->point[j].x)/2.0;
>         lar->label_points[lar->num_label_points].y = (p->point[j-1].y + p->point[j].y)/2.0;
> ```

Ok, so I think what the changes do. Ok with me to move forward... --Steve

**Pull request merged**
