### PR TITLE
Add 4 new COMPOSITE.COMPOP blending operations (in particular hsl-color)

### PR DESCRIPTION
**Pull request by rouault**
Cf https://pycairo.readthedocs.io/en/latest/reference/enums.html#cairo.Operator.HSL_HUE

- "hsl-hue": Creates a color with the hue of the source and the saturation and luminosity of the target.
- "hsl-luminosity": Creates a color with the luminosity of the source and the hue and saturation of the target. This produces an inverse effect to hsl-color
- "hsl-saturation": Creates a color with the saturation of the source and the hue and luminosity of the target. Painting with this mode onto a gray area produces no change.
- "hsl-color": Creates a color with the hue and saturation of the source and the luminosity of the target. This preserves the gray levels of the target and is useful for coloring monochrome images or tinting color images.

That last mode is typical the most useful, for example when draping a colorized terrain onto a hillshade layer, or to colorize a greyed LIDAR shaded surface model with a green mask of a canopy model.

Ambiant occlusion LIDAR:
ambiant_occlusion_lidar
combined with Canopy Model blended on top of it with "hsl-color" at 100% opacity
canopy_model
results in:
ambiant_occlusion_lidar_colored_with_canopy

----

Implemented in the Cairo backend using the corresponding Cairo operators (which ultimately go to using Pixman), or in the AGG backend, by manually extracting the related Pixman code and adapting it to AGG (or when building WITH_PIXMAN=ON, by using the Pixman operation)

Note: if using OPACITY < 100 with the Cairo backend (or AGG WITH_PIXMAN=ON), there's a bug in current Pixman versions that result in wrong colors. Cf https://gitlab.freedesktop.org/pixman/pixman/-/merge_requests/97 The adaptation in the AGG backend isn't affected by this bug.

(note: this is intended to be 8.4.0 material, at least shouldn't be a reason to delay 8.2.0)

### CODE REVIEW

**Comment by jmckenna** [comment]
@rouault thanks for these additions.  Regarding Pixman, I cringe to remember the many [issues with OPACITY](https://github.com/MapServer/MapServer/issues/5343) in MapServer with `-DWITH_PIXMAN=1`, as all packagers since then have to disable PIXMAN in MapServer with `-DWITH_PIXMAN=0` ...or maybe I am misunderstanding your comments above with AGG?

**Comment by rouault** [comment]
> Regarding Pixman, I cringe to remember the many [issues with OPACITY](https://github.com/MapServer/MapServer/issues/5343) in MapServer with `-DWITH_PIXMAN=1`,

This older pixman issue is not the same as the one I noticed for this development, which is only used by the 4 new operators.

**Comment by rouault** [comment]
if there are no further remark on this PR, I'll merge it in a few days

**Comment by sdlime** [comment]
+1 from me.

**Pull request merged**
