### PR TITLE
WFS: limit SQL Select to required fields for faster data retrieval

### PR DESCRIPTION
**Pull request by rouault**
Co-authored-by: Seth G <sethg@geographika.co.uk>

### CODE REVIEW

**Comment by rouault** [comment]
Supersedes https://github.com/mapserver/mapserver/pull/5997
CC @geographika

**Comment by geographika** [comment]
Thanks @rouault !
Built and tested locally, and all working fine. 
This update greatly improves WFS performance when requesting a subset of layer fields. 

One question/confirmation - any fields referenced in a `CLASS` are selected at the database level even if never used for a WFS request (this was also the case in my previous pull request) - I presume there is no way to get round this due to `buildLayerItemList` also handling fields referenced in `FILTER`, `CLUSTER` etc. ?

**Comment by rouault** [comment]
> any fields referenced in a `CLASS` are selected at the database level even if never used for a WFS request (this was also the case in my previous pull request) - I presume there is no way to get round this due to `buildLayerItemList` also handling fields referenced in `FILTER`, `CLUSTER` etc. ?

yes, msLayerWhichItems() doesn't know the calling context, so there might be things that are irrelevant to WFS. It would require to know which items are needed for which context.

**Comment by jmckenna** [comment]
thanks @rouault & @geographika !!

**Pull request merged**
