### PR TITLE
Add Support for PHP-NG MapScript (via SWIG)

### PR DESCRIPTION
**Pull request by AlexanderGabriel**
Next try.
This will add support for PHP-MapScript via SWIG.
There is still work:
- There is a warning when generating the wrapper for a method called "empty". It is renamed to c_empty. You'll see this when compiling. How do "we" handle this?
- On Windows, there is a Problem with swig. It will not be possible to compile thread-safe extensions with swig 3.0.12 but if you build current swig from git build you can generate code that compiles. NTS-Extension work.
- Build Instruction need to be updated. Especially for Windows. I have some batch files here that will do everything. I can update the windows readmes.

Linux users should have no problems building it. I tested on Debian Testing a few weeks ago. Functionality should be there but i did really only do some basic tests...

Kind Regards,
Alex

### CODE REVIEW

**Comment by AlexanderGabriel** [comment]
Don't know how to fix this but i can provide you with information about my steps to build. maybe, you can adopt this to appveyor and make that work. i can give you write access to my repo if you want.

- First install git and VS 2017 Community
- Create Directory C:\dev\work
- Open Native Tools Command Prompt
First we build PHP (Some Commands are to clean up old runs)
- cd C:\dev\work && rmdir /s /q C:\dev\work\php-sdk
- git clone https://github.com/Microsoft/php-sdk-binary-tools.git php-sdk
- cd c:\dev\work\php-sdk
- set VS_VERSION=%VSCMD_VER:~0,2%
- phpsdk-vc%VS_VERSION%-%VSCMD_ARG_TGT_ARCH%.bat
- phpsdk_buildtree phpmaster
- cd C:\dev\work\php-sdk\phpmaster\%PHP_SDK_VC%\%VSCMD_ARG_TGT_ARCH% && rmdir /s /q C:\dev\work\php-sdk\phpmaster\%PHP_SDK_VC%\%VSCMD_ARG_TGT_ARCH%\php-src
- git clone https://github.com/php/php-src.git
- cd C:\dev\work\php-sdk\phpmaster\%PHP_SDK_VC%\%VSCMD_ARG_TGT_ARCH%\php-src
- phpsdk_deps --update --branch master
- buildconf
- configure --enable-snapshot-build
- nmake snap

Now get GISInternals Dependencies (stay in PHP-SDK-Shell to have wget and unzip available):
- cd C:\dev\work
- if not exist C:\dev\packages mkdir C:\dev\packages
- if not exist C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%\ mkdir C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%\
- rmdir /s /q C:\dev\work\gisinternals%VSCMD_ARG_TGT_ARCH%
- mkdir C:\dev\work\gisinternals%VSCMD_ARG_TGT_ARCH%
- if not exist C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH% mkdir C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%
- set GISInternalsArchitecture=-
- if %VSCMD_ARG_TGT_ARCH% == x64 set GISInternalsArchitecture=-%VSCMD_ARG_TGT_ARCH%-
- if not exist C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%\release-1911%GISInternalsArchitecture%dev.zip wget -O C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%\release-1911%GISInternalsArchitecture%dev.zip http://download.gisinternals.com/sdk/downloads/release-1911%GISInternalsArchitecture%dev.zip
- unzip -q -o C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%\release-1911%GISInternalsArchitecture%dev.zip -d C:\dev\work\gisinternals%VSCMD_ARG_TGT_ARCH%
- if not exist C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%\release-1911%GISInternalsArchitecture%gdal-mapserver-src.zip wget -O C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%\release-1911%GISInternalsArchitecture%gdal-mapserver-src.zip http://download.gisinternals.com/sdk/downloads/release-1911%GISInternalsArchitecture%gdal-mapserver-src.zip
- unzip -q -o C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%\release-1911%GISInternalsArchitecture%gdal-mapserver-src.zip -d C:\dev\work\gisinternals%VSCMD_ARG_TGT_ARCH%
- if not exist C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%\release-1911%GISInternalsArchitecture%gdal-mapserver-libs.zip wget -O C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%\release-1911%GISInternalsArchitecture%gdal-mapserver-libs.zip http://download.gisinternals.com/sdk/downloads/release-1911%GISInternalsArchitecture%gdal-mapserver-libs.zip
- unzip -q -o C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%\release-1911%GISInternalsArchitecture%gdal-mapserver-libs.zip -d C:\dev\work\gisinternals%VSCMD_ARG_TGT_ARCH%
- if not exist C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%\release-1911%GISInternalsArchitecture%gdal-mapserver.zip wget -O C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%\release-1911%GISInternalsArchitecture%gdal-mapserver.zip http://download.gisinternals.com/sdk/downloads/release-1911%GISInternalsArchitecture%gdal-mapserver.zip
- unzip -q -o C:\dev\packages\gisinternals%VSCMD_ARG_TGT_ARCH%\release-1911%GISInternalsArchitecture%gdal-mapserver.zip -d C:\dev\work\gisinternals%VSCMD_ARG_TGT_ARCH%


Now Build Mapserver
- cd C:\dev\work && rmdir /s /q C:\dev\work\mapserver
- git clone https://github.com/AlexanderGabriel/mapserver
- cd C:\dev\work\mapserver && rmdir /s /q C:\dev\work\mapserver\build
- git fetch origin
- git checkout -b master-PHP-Mapscript-NG origin/master-PHP-Mapscript-NG
- mkdir C:\dev\work\mapserver\build
- cd C:\dev\work\mapserver\build
- cmake C:\dev\work\mapserver -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -Wno-dev -DCMAKE_INSTALL_PREFIX=C:\dev\builds\mapserver -DCMAKE_PREFIX_PATH=C:\dev\work\gisinternals%VSCMD_ARG_TGT_ARCH%;C:\dev\work\gnulib\lib;C:\dev\work\gnulib\include;C:\dev\work\gisinternals%VSCMD_ARG_TGT_ARCH%\lib;C:\dev\work\gisinternals%VSCMD_ARG_TGT_ARCH%\include -DREGEX_DIR=C:\dev\work\regex-0.12
- cmake C:\dev\work\mapserver -DWITH_POSTGIS=0 -DWITH_PROTOBUFC=0 -DWITH_THREAD_SAFETY=1
- cmake C:\dev\work\mapserver -DWITH_PHPNG=1 -DSWIG_EXECUTABLE=C:\dev\work\swig-cygwin\build\swig.exe -DSWIG_DIR=C:\dev\work\swig-cygwin\build
- cmake --build C:\dev\work\mapserver\build

And not to forget: You need a build of current developement version of SWIG in C:\dev\work\swig-cygwin\build... But i have a CMake makefile for SWIG here. I can push this to my fork of SWIG so we can use it from there to build it during the test. Alternatively disable ZTS when building PHP and change -DWITH_THREAD_SAFETY=1 to -DWITH_THREAD_SAFETY=0.

**Comment by AlexanderGabriel** [comment]
Forgot gnulib and activated AppVeyor for my rep right now. Let me try to fix this. I'll be back ;)

**Comment by AlexanderGabriel** [comment]
I don't think, this errors are from me, because it doesn't even try to compile with phpng-support.

**Comment by geomunion** [comment]
Hmmm,
@AlexanderGabriel , could you verify the output of `C:/projects/mapserver/build/swig.exe -swiglib`? It seems to be empty. ...
Maybe adding `swig.exe -swiglib` to appveyor.yml - right after `cmake --build .` gives some useful informations.

... I think this causes the `CMake Error at mapscript/python/CMakeLists.txt:2 (INCLUDE):` (because ${SWIG_USE_FILE} is unset).
And so `swig_add_library` is undefined, because of the failed include.

(on my Debian testing `swig -swiglib` returns `/usr/share/swig3.0`)

P.S.: I don't know how to build on Windows, but i'm missing something like `make install` after building. Maybe for copying files into the right place ...

-- Tobias

**Comment by AlexanderGabriel** [comment]
Good hint, Tobias. Thank you. I had a wrong path to swig.exe and path to swig lib was wrong because i used cygwin to configure it and built it with cmake on windows native.
this error is gone but now theres new ones...
https://ci.appveyor.com/project/AlexanderGabriel/mapserver

Actually i'm not that good in building software on windows aswell. just wanted to have a current mapserver on windows 2 years ago and so i came here. now i want it to work with php7 so i'm trying to get this running but cmake is awesome makes everything much easier.

I don't know if there is a need for make install after building. Don't think, there are default paths. i always copy the stuff where i need it to be. i think this is a good question for a discussion on developer mailing list.

**Comment by AlexanderGabriel** [comment]
csharp works local if I run cmake --build twice
if I disable csharp building and python testing it works but that doesnt help much, right? ;)

**Comment by geographika** [comment]
@AlexanderGabriel - Python3 fails if you use the version of SWIG included in the SDK (SWIG-1.3.39) - however this is not yet being tested in Appveyor so wouldn't cause the build to fail. C# fails if you use a newer version of SWIG (see #5575). 
Not sure if that is any help - I can look into any Python tests that are failing if you have a link to an Appveyor log.

**Comment by AlexanderGabriel** [comment]
@geographika - Python 2 builds.
My version at https://github.com/AlexanderGabriel/mapserver/tree/appveyor-fixing builds and SWIG 4.0.0
I don't have the error from https://github.com/mapserver/mapserver/issues/5575.
"mine" looks like that:
grafik

Scanning dependencies of target mapscript
[ 99%] Building C object mapscript/csharp/CMakeFiles/mapscript.dir/mapscriptCSHARP_wrap.c.obj
mapscriptCSHARP_wrap.c
c:\dev\work\mapserver\build\mapscript\csharp\mapscriptcsharp_wrap.c(1715) : warning C4715: 'mapObj_draw': not all control paths return a value
[100%] Linking C shared module mapscript.dll
   Creating library mapscript.lib and object mapscript.exp
Compiling c# source files
%MAPSCRIPT_SNK:/=\*
Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
        0 Datei(en) kopiert.
NMAKE : fatal error U1077: 'copy' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.







if i just repeat the build command, it works...



Here is the failed build with the failing python tests: https://ci.appveyor.com/project/AlexanderGabriel/mapserver/build/1.0.21/job/hewueod67w0j823h

**Comment by geographika** [comment]
@AlexanderGabriel - I was looking at the Python CMakeLists yesterday, and there is likely an issue with getting the path to the _mapscript.pyd file, hence the tests are all failing as it is not on the PYTHONPATH. I'll be looking at it again this weekend (should be a case of switching to a $<TARGET_FILE> expression as outlined at https://cmake.org/cmake/help/v3.0/policy/CMP0026.html

For the .NET bindings - I couldn't get them to work with SWIG 3.0 so unlikely they will work with 4.0.

**Comment by geomunion** [comment]
Hi @AlexanderGabriel ,
if i revert your changes of `mapscript/`mapscript.i` (https://github.com/mapserver/mapserver/pull/5619/commits/2a496159d35d8a475b33bcad2981742e81466e08#diff-bed01f9bad2034b8438522c5abd14a15) building with csharp passes.

see: (based on your first pull request)
* https://github.com/geomunion/mapserver/commits/feature-php7_experimental
* https://ci.appveyor.com/project/geomunion/mapserver/build/1.0.6

**Comment by AlexanderGabriel** [comment]
HI @geomunion ,
this is for sure a typo from me. there should be something else (swigphp/7?) but for sure not swigsharp.
I'll have a look at this later.
Thank you.

**Comment by geomunion** [comment]
Hi @AlexanderGabriel ,
SWIGPHP works for PHP5 and PHP7, SWIGPHP7 only for PHP7 and SWIGPHP5 only for PHP5.
I used SWIGPHP7 for injecting module infos to phpinfo() - see: https://github.com/geomunion/mapserver/commit/9e3674e7f6df2d9f05ea9dafde4f5901cf6918fb

But renaming the module this way may have other side effects.(?) Maybe
`set_target_properties(${SWIG_MODULE_mapscript_REAL_NAME} PROPERTIES PREFIX "")` at mapscript/phpng/CMakeLists.txt  needs to reflect the new name...  I don't know ...

**Comment by AlexanderGabriel** [comment]
Opened new Pull-Request: https://github.com/mapserver/mapserver/pull/5623
Closing this.

**Pull request closed without merging**
