### PR TITLE
add perl to travis

### PR DESCRIPTION
**Pull request by AndyColson**
A start just to see if it'll build and test.  Only one test and one example so far.  If this goes ok, then I'll add more.

### CODE REVIEW

**Comment by geographika** [comment]
@AndyColson - looks great so far. You can see build and test output at https://travis-ci.org/mapserver/mapserver/jobs/515505933

**Comment by sdlime** [comment]
Great addition... Should this be completed and merged as part of beta2?

**Comment by AndyColson** [comment]
I have two small swig changes I'd like to make:
1) enable msIO_getAndStripStdoutBufferMimeHeaders for everything. (why is it python only?)
2) clean up compiler warning in image.i (and also return null on error, rather than broken object)

Would that be ok to check in?  If I check it in, and you don't like it, I dunno how to un-check-out.

**Comment by AndyColson** [comment]
Ahh, bummer, my merge seems to have picked up the version change in CMakeLists.txt.  How do I undo that?

**Comment by geographika** [comment]
@AndyColson - is this pull request ready to merge to a new 7.4-beta release?

**Comment by AndyColson** [comment]
Yes.

**Comment by geographika** [comment]
@AndyColson - thanks very much for setting this up

**Pull request merged**
