### PR TITLE
Addressed issues identified in issue #6463.

### PR DESCRIPTION
**Pull request by sdlime**
Addressed issues identified by @geographika and @jmckenna. Note I left style->angle check at 0 to 360.

### CODE REVIEW

**Review by geographika — APPROVED** [review]
Looks good to me, and fine to leave the ANGLE validation as-is. I'll update https://github.com/MapServer/MapServer-documentation/pull/663 with these changes.

**Comment by sdlime** [comment]
Thanks @geographika. Will give @jmckenna a little while to test before merging...

**Comment by jmckenna** [comment]
Thanks @sdlime I am testing now...

**Review by jmckenna — COMMENTED** [review]
@sdlime I tested the issues that I reported earlier, here's the feedback:

6. line number in error messages --> works well.  For example (not sure why map2img repeats it twice though, but that's very minor) :
```
loadStyle(): General error message. Invalid WIDTH, must be greater than or equal to 0 (line 171)
loadStyle(): General error message. Invalid WIDTH, must be greater than or equal to 0 (line 171) <br>
```
7. test for WIDTH >=0     <-- works well

8. MapScript's save() method for mapObj --> now saves the mapfile with a valid QUERYMAP, such as:
```
  QUERYMAP
    STATUS OFF
    STYLE HILITE
  END # QUERYMAP
```
*new*

9. a valid `MINSCALEDENOM 0` in a LAYER fails, such as:
```
   LAYER
     ...
     MINSCALEDENOM 0
     MAXSCALEDENOM 2539
     ...
   END # layer
```
with error message:
```
getDouble(): Symbol definition error. Parsing error near (0):(line 9281)
getDouble(): Symbol definition error. Parsing error near (0):(line 9281) <br>
```

**Review by jmckenna — APPROVED** [review]

**Comment by sdlime** [comment]
@jmckenna, why should MINSCALEDENOM 0 be considered valid?

**Comment by jmckenna** [comment]
> @jmckenna, why should MINSCALEDENOM 0 be considered valid?

This is the case for all mapfiles generated by the "Basemaps" sub-project of MapServer.

**Comment by sdlime** [comment]
> > @jmckenna, why should MINSCALEDENOM 0 be considered valid?
> 
> This is the case for all mapfiles generated by the "Basemaps" sub-project of MapServer (which are ~10,000 lines long), and, with a user hat on, this makes sense to me. Also, I'm for less-breaking of existing mapfiles, especially huge ones like this that we manage under our umbrella.

Ok, I get it. The min/maxscaledenom values are used to limit processing and aren't used in computations so allowing GTE 0 is ok. Should that be the consistent for web, layer, class, style and label objects? @geographika, what do you think? Easy change on my end and now's the time.

**Comment by sdlime** [comment]
Re: 8. @jmckenna, can you check a QUERYMAP with SIZE -1 -1 - so written by an older version? That should be ok as well based on my testing.

**Comment by jmckenna** [comment]
> 
> Ok, I get it. The min/maxscaledenom values are used to limit processing and aren't used in computations so allowing GTE 0 is ok. Should that be the consistent for web, layer, class, style and label objects? @geographika, what do you think? Easy change on my end and now's the time.

Yes I believe this should be consistent for the other scaledenoms in objects.

**Comment by jmckenna** [comment]
> Re: 8. @jmckenna, can you check a QUERYMAP with SIZE -1 -1 - so written by an older version? That should be ok as well based on my testing.

True, thanks, confirmed here that QUERYMAP SIZE -1 -1 is now accepted.

**Comment by sdlime** [comment]
> > Ok, I get it. The min/maxscaledenom values are used to limit processing and aren't used in computations so allowing GTE 0 is ok. Should that be the consistent for web, layer, class, style and label objects? @geographika, what do you think? Easy change on my end and now's the time.
> 
> Yes I believe this should be consistent for the other scaledenoms in objects.

Changing to allow 0 or higher for all minx/maxscaledenom values then.

**Comment by jmckenna** [comment]
> Changing to allow 0 or higher for all minx/maxscaledenom values then.

Yes I believe so.   I think it makes sense to a user.  (staying away from technical debates though ha)

**Comment by geographika** [comment]
> Ok, I get it. The min/maxscaledenom values are used to limit processing and aren't used in computations so allowing GTE 0 is ok. Should that be the consistent for web, layer, class, style and label objects? @geographika, what do you think? Easy change on my end and now's the time

It looks like it is used in [a few Mapfiles in "the wild"](https://github.com/search?q=%22MINSCALEDENOM+0%22++extension%3Amap&type=Code&ref=advsearch&l=&l=) so seems a good idea to allow it. Consistency across the Mapfile objects sounds good.

**Comment by geographika** [comment]
@sdlime - docs updated in https://github.com/MapServer/MapServer-documentation/pull/663 to reflect the changes here

**Pull request merged**
