### PR TITLE
Branch 8 0

### PR DESCRIPTION
**Pull request by jbfrd**
Reimplementation of the pasteImage() and saveWebImage() methods in the imageObj class in mapscript/swiginc/image.i

### CODE REVIEW

**Comment by jmckenna** [comment]
Thanks @jbfrd   Can you briefly describe the contents of this pull request?

**Comment by jmckenna** [comment]
@jbfrd Please can you change this pull request to the `main` branch?  thanks.

**Comment by jbfrd** [comment]
> @jbfrd Please can you change this pull request to the `main` branch? thanks.

Sorry, but the path mapscript/... is missing in the `main` branch.

**Comment by jmckenna** [comment]
> > @jbfrd Please can you change this pull request to the `main` branch? thanks.
> 
> Sorry, but the path mapscript/... is missing in the `main` branch.

see `/src/mapscript`

**Pull request closed without merging**
