### PR TITLE
maplexer.l: avoid non-null terminated msyystring_buffer that can cause read heap-buffer-overflow

### PR DESCRIPTION
**Pull request by rouault**
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52175

### CODE REVIEW

**Comment by sdlime** [comment]
Won't we have the same problem then with getDouble or anywhere else we use "Parsing error near (%s)"?

**Comment by rouault** [comment]
@sdlime On closer investigation, the issue was in maplexer.l where msyystring_buffer was not always null-terminated

**Comment by sdlime** [comment]
Ah... Might still be good to consider trimming msyystring_buffer when using outputting the location where the error was encountered. Either the whole string if the buffer is less than 20 characters or the first 17 characters followed by '...'. Otherwise an unterminated quoted string mistake could cough up more text than necessary.  What do you think?

**Comment by rouault** [comment]
> What do you think?

potential improvement, but not in my todo list currently :-)

**Comment by sdlime** [comment]
> not in my todo list currently :-)

Absolutely!

**Comment by rouault** [comment]
manually backported to 7.6 per https://github.com/MapServer/MapServer/pull/6688

**Pull request merged**
