### PR TITLE
Metadata: use attribution_title if available (#6166)

### PR DESCRIPTION
**Pull request by tomkralidis**
Implements #6166 

In addition, removes erroneous default date output.

### CODE REVIEW

**Review by rouault — COMMENTED** [review]
I'm not super qualified to comment on this.
Just 2 remarks;
- the mention "In addition, removes erroneous default date output." should be added to the commit message itself. (ideally this would have been a separate commit)
- I guess we would need extending an existing test to set "attribution_title" and see its effect in the XML output

**Comment by tomkralidis** [comment]
Thanks for the feedback.  Split into two commits with updated test.

**Comment by jmckenna** [comment]
thanks @tomkralidis Again, although it is only case, maybe rename your local repository from 'mapserver' to 'MapServer', just in case it makes the other Github tools like backport-bot choke down the road (although this PR will not be backported).   thanks again!

**Comment by tomkralidis** [comment]
Thanks again @jmckenna, done: https://github.com/tomkralidis/MapServer

**Pull request merged**
