### PR TITLE
Fix most of remaining Coverity scan warnings with high priority

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by sdlime** [comment]
+1 - Thanks @rouault!

**Comment by jmckenna** [comment]
Great work @rouault !!

**Comment by sdlime** [comment]
Should these (and other recent commits related to scanning) be pushed to older branches as well?

**Comment by rouault** [comment]
> Should these (and other recent commits related to scanning) be pushed to older branches as well?

I'm afraid we can't realisticly pretend to be able to maintain secure more than one release branch at a time..

**Comment by jmckenna** [comment]
My personal opinion (I wrote this in some response, but I can't remember if it was public): I'd like to see our efforts (which are unfunded of course, and limited) to sticking with supporting the most recent release branch (branch-7-6), I'm not for supporting older unmaintained branches (such as branch-7-4 etc).

**Pull request merged**
