### PR TITLE
Add PHP7.x support

### PR DESCRIPTION
**Pull request by bjoernboldt**
I added some macros and made some changes to the structs in php_mapcript.h for PHP7. So the code is now compatible with PHP5.x and PHP7.x.

### CODE REVIEW

**Comment by sdlime** [comment]
So this gives us PHP7 support 2 ways - via php_mapscript and Swig? --Steve

**Comment by nboisteault** [comment]
Thank you very much! Will it land in mapserver 7.0 soon?

**Comment by sdlime** [comment]
I don't know quite yet. Assuming it works - I'm not a PHP user and so not in a position to test - I don't know why not. This probably needs to be taken to the mapserver-dev list for discussion. Might be good if you brought it up? There is also SWIG-based PHP 7.0 effort... --Steve

**Comment by stoecker** [comment]
CMake says "-- Found PHP5-Version 7.2.5 (using /usr/bin/php-config)". Text should be adapted ;-)

**Comment by geographika** [comment]
PHP-NG support added with #5675

**Pull request closed without merging**
