### PR TITLE
revert backport workflow

### PR DESCRIPTION
**Pull request by jmckenna**
- go back to our working workflow for backports (as it has been working for 13 months smoothly)
- will continue to monitor m-kuhn/backport and its comparisons to Gaurav0/backport (following both for activity)

### CODE REVIEW

**Comment by rouault** [comment]
a "git revert" would be the nominal command to do the revert. I can do that if you wish

**Comment by jmckenna** [comment]
I expected this comment coming fast from you :)  Sure whichever you wish.

**Comment by jmckenna** [comment]
Good thing about this method is it gives a chance for discussion.  Anyway, I'm fine for reverting manually.

**Comment by rouault** [comment]
>  Anyway, please do that manually instead yes.

done. Force-pushed on your current branch / this PR.

**Comment by jmckenna** [comment]
thanks!  fast.  Appreciate it.

**Comment by jmckenna** [comment]
oh darn, must be friday night.....

**Pull request merged**
