### PR TITLE
Make sure requested class with mode=legendicon is not negative.

### PR DESCRIPTION
**Pull request by sdlime**

### CODE REVIEW

**Comment by jmckenna** [comment]
Thanks Steve, I think we can also backport this to 7-6....(adding label now)

**Comment by sdlime** [comment]
> Thanks Steve, I think we can also backport this to 7-6....(adding label now)

Definitely, can go back further too if those backports work.

**Comment by sdlime** [comment]
> Thanks Steve, I think we can also backport this to 7-6....(adding label now)

@jmckenna , the backport failed. Do you know if it's an action issue or something else? The change was minor and should have backported cleanly.

**Comment by jmckenna** [comment]
@sdlime I'll take a look...

**Comment by jmckenna** [comment]
cherry-picked manually to the 7-6 branch (https://github.com/MapServer/MapServer/commit/0901b574dd9da8fc2577a55b416d56b8189dca86)

**Comment by jmckenna** [comment]
(I'm not aware of a problem with the GitHub action, it has been working great...anyway one manual cherry-pick is ok)

**Pull request merged**
