### PR TITLE
Fix for #6601 - ensure a valid WHERE clause is created in all cases

### PR DESCRIPTION
**Pull request by geographika**
Return a non-empty string, so in cases where `!BOX!` is used a valid WHERE clause is still created. See #6601. 

The logic currently relies on returning empty strings when invalid WHERE clauses are created to throw an error, so the least intrusive fix is to create a "fake" where clause to return all records and ensure the check for an empty string is skipped.

### CODE REVIEW

**Comment by sdlime** [comment]
Thanks for taking this on @geographika! Fix seems ok to me at first glance...

**Comment by PostholerCom** [comment]
Thank you for looking into this!

**Comment by jmckenna** [comment]
I've added an msautotest for the boxtoken for PostGIS, let's see how it goes...

**Comment by jmckenna** [comment]
darn, it's likely failing because of libpng version differences (for the msautotest)...will have to tackle tomorrow...

**Comment by geographika** [comment]
> darn, it's likely failing because of libpng version differences (for the msautotest)...will have to tackle tomorrow...

I was wondering how you generated msautotest images on Windows (or Mac?). A WFS test could be easier?

**Review by jmckenna — APPROVED** [review]

**Comment by jmckenna** [comment]
thanks @geographika & @PostholerCom !

**Pull request merged**
