### PR TITLE
Transfer geometries in binary from Postgres.

### PR DESCRIPTION
**Pull request by pvalsecc**
Use a trick to have the other fields (when any) still transfered in
text form.

### CODE REVIEW

**Comment by pvalsecc** [comment]
The Travis failure is because of those two files that have a bad (according to pep8) indentation:
* python/plugins/processing/algs/grass/GrassAlgorithm.py
* python/plugins/processing/algs/grass7/nviz7.py

I didn't touch those files with my commit and autopep8 on my machine does not agree with the one on Travis.

**Comment by tbonfort** [comment]
@pvalsecc the failure is
```
######################################
# query => query_postgis_test012.txt
######################################
--- ../expected/query_postgis_test012.txt	2016-01-20 13:18:30.446291031 +0000
+++ query_postgis_test012.txt	2016-01-20 13:20:03.918291031 +0000
@@ -1,3 +0,0 @@
-Marshall:MARS 
-
-
```

**Comment by pvalsecc** [comment]
Thanks Tomas, big mix up on my side... I should not do two PRs at the same time ;-)

I'll investigate that.

**Comment by pvalsecc** [comment]
Can somebody have a look at this PR, please?

**Comment by sdlime** [comment]
Looks ok to me but I'm no expert on the PostGIS code. @tbonfort or @pramsey, any comment?

**Comment by pramsey** [comment]
If it regresses, I'm OK w/ it

**Comment by tbonfort** [comment]
@pvalsecc I think this should be a change for 7.2 rather than 7.0 ?
I'm no expert on the subject at hand. Are there any issues you think may arise if we apply this?

**Comment by pvalsecc** [comment]
@tbonfort, it's as you guys want. I don't mind. I worked on 7.0 because it's the version I was using in prod and I didn't want to risk some incompatibilities with my mapfiles. But I guess transplanting the patch shouldn't be a problem.

**Comment by pvalsecc** [comment]
I've created another PR based on master: https://github.com/mapserver/mapserver/pull/5238

**Comment by tbonfort** [comment]
@pvalsecc If you can rework this to be able to select the transfer mode at runtime rather than compile time, and that the default remains to the current behavior, then we could apply this to the stable 7.0 branch. If not, let's close this issue and focus only on 7.2 in #5238.

**Comment by pvalsecc** [comment]
@tbonfort, I don't see the point. Closing this PR.

**Pull request closed without merging**
