### PR TITLE
Allow OFFSET working on polygon layers

### PR DESCRIPTION
**Pull request by mkofahl**
Allow OFFSET working on polygon layers by changing shape type to line before passing it to geos, which will throw 'BufferBuilder::bufferLineSingleSided only accept linestrings' otherwise (which isn't fully passed to MapServer, actually). Requires #5099.

### CODE REVIEW

**Comment by mkofahl** [comment]
@tbonfort can you comment on this?

**Comment by tbonfort** [comment]
@mkofahl in tbonfort/msautotest@ebd1bf6 I have tried to create a simple test case to activate this. Is this what you are trying to support.
With your patch applied, I get
```
[Wed Feb 24 14:31:20 2016].987766 msGEOSError(): GEOS library error.
```
Without your patch
```
[Wed Feb 24 14:28:01 2016].496595 msGEOSError(): GEOS library error. 
[Wed Feb 24 14:28:01 2016].497992 msGEOSError(): GEOS library error. 
[Wed Feb 24 14:28:01 2016].498786 msGEOSError(): GEOS library error. 
[Wed Feb 24 14:28:01 2016].499733 msGEOSError(): GEOS library error.
```

**Comment by geographika** [comment]
Related - #5442

**Comment by jmckenna** [comment]
@mkofahl can you possibly rebase this against master (instead of branch-7-0) ?

**Comment by ejn** [comment]
@jmckenna rebased and extended with test case and resubmitted against master as #6132

**Comment by jmckenna** [comment]
thanks @ejn !!

**Pull request closed without merging**
