### PR TITLE
Content Dependent Legend Rendering Tracking (RFC 101)

### PR DESCRIPTION
**Pull request by tbonfort**
Track development around rfc101: http://mapserver.org/development/rfc/ms-rfc-101.html

### CODE REVIEW

**Comment by ruhri** [comment]
The Feature seems to broken with Mapserver 7.0.0 - Examples:

without Context-Legend - OK: http://geodaten.metropoleruhr.de/spw/spw_web?language=ger&&SERVICE=WMS&VERSION=1.3.0&SLD_VERSION=1.1.0&REQUEST=GetLegendGraphic&FORMAT=image/png&LAYER=oepnv_linien&STYLE=&

with Context-Legend - ERROR (Extent is valid):
http://geodaten.metropoleruhr.de/spw/spw_web?SERVICE=WMS&VERSION=1.3.0&SLD_VERSION=1.1.0&REQUEST=GetLegendGraphic&FORMAT=image/png&LAYER=oepnv_linien&STYLE=&BBOX=361299.31917663925560191,5701245.71691642235964537,362276.95459430309711024,5701856.90441704634577036&CRS=EPSG:25832&WIDTH=1478&HEIGHT=925

Passing the erroneous request directly to mapserv in bash, i get a "Speicherzugriffsfehler" ( in english: segfault) --> mapserv crashes

**Comment by tbonfort** [comment]
@ruhri can you provide a gdb backtrace of the crash, or a complete testcase that would allow me to reproduce this

**Comment by ruhri** [comment]
Hi tbonfort, thank you for your efforts.
Further investigation becomes more strange:
I like to use "Named group layers" as stated in http://mapserver.org/development/rfc/ms-rfc-75.html#named-group-layers.
mapfile-example: https://svn.osgeo.org/mapserver/sandbox/inspire_soc2011/msautotest/wxs/wms_inspire.map

my personal simplified case -which leads to the above posted segfault problem - is the following layer structure (it shows public transportation lines...):

	# Gruppenlayer: ÖPNV
	LAYER
		NAME "oepnv"
		METADATA
			"ows_srs"								"EPSG:25832 EPSG:25833 EPSG:3857 EPSG:4258 EPSG:4326 EPSG:31466 EPSG:31467 EPSG:31468 EPSG:31469 EPSG:900913"
			"ows_extent"							"300000.0 5620000.0 440000.0 5770000.0"
			"ows_title"								"ÖPNV"
			"ows_abstract"							"Ebene ÖPNV"
		END
		TYPE POINT
	END

	# Layer: ÖPNV-Liniennetz
	LAYER
		NAME "oepnv_linien"
		DATA "/data/spw/spw_web/oepnv/linien"

		METADATA
			"wms_enable_request"					"*"
			"wfs_enable_request"					"*"
			"wfs_getfeature_formatlist"				"gml2,gml3,shapezip,csv,geojson,gpx"
			"ows_srs"								"EPSG:25832 EPSG:25833 EPSG:3857 EPSG:4258 EPSG:4326 EPSG:31466 EPSG:31467 EPSG:31468 EPSG:31469 EPSG:900913"
			"ows_extent"							"300000.0 5620000.0 440000.0 5770000.0"
			"wms_layer_group"						"/oepnv"
			"ows_title"								"ÖPNV-Liniennetz"
			"ows_abstract"							"Ebene ÖPNV-Liniennetz"
			"gml_featureid"							"gid"
			"gml_include_items"						"all"
			"gml_geometries"						"geom"
			"gml_geom_type"							"multiline"
			"gml_verkehrsm_alias"					"verkehrsmittel"
		END

		TYPE LINE

		PROJECTION
			"init=epsg:25832"
		END

		MAXSCALEDENOM 501000
		MINSCALEDENOM 1

		UNITS METERS
		CLASSITEM 'verkehrsm'
		CLASS
			NAME "Bus"
			EXPRESSION 'Bus'
			STYLE
				WIDTH 1.5
				COLOR 0 170 50
				OUTLINECOLOR 255 255 255
				OUTLINEWIDTH 0.5
				LINEJOIN ROUND
			END
		END
		CLASS
			NAME "Straßenbahn"
			EXPRESSION 'Straßenbahn'
			STYLE
				WIDTH 2.2
				COLOR 204 0 0
				OUTLINECOLOR 255 255 255
				OUTLINEWIDTH 0.7
				LINEJOIN ROUND
			END
		END
		CLASS
			NAME "Stadtbahn"
			EXPRESSION 'Stadtbahn'
			STYLE
				WIDTH 3.0
				COLOR 21 106 184
				OUTLINECOLOR 255 255 255
				OUTLINEWIDTH 1
				LINEJOIN ROUND
			END
		END
		CLASS
			NAME "U-Bahn"
			EXPRESSION 'U-Bahn'
			STYLE
				WIDTH 3.0
				COLOR 21 106 184
				OUTLINECOLOR 255 255 255
				OUTLINEWIDTH 1
				LINEJOIN ROUND
			END
		END
	END

MAPFILE VERSION2: 
if I just move the named group below it's sublayer in the mapfile (the only change!!!), the content dependent legend works well:

	# Layer: ÖPNV-Liniennetz
	LAYER
		NAME "oepnv_linien"
		DATA "/data/spw/spw_web/oepnv/linien"

		METADATA
			"wms_enable_request"					"*"
			"wfs_enable_request"					"*"
			"wfs_getfeature_formatlist"				"gml2,gml3,shapezip,csv,geojson,gpx"
			"ows_srs"								"EPSG:25832 EPSG:25833 EPSG:3857 EPSG:4258 EPSG:4326 EPSG:31466 EPSG:31467 EPSG:31468 EPSG:31469 EPSG:900913"
			"ows_extent"							"300000.0 5620000.0 440000.0 5770000.0"
			"wms_layer_group"						"/oepnv"
			"ows_title"								"ÖPNV-Liniennetz"
			"ows_abstract"							"Ebene ÖPNV-Liniennetz"
			"gml_featureid"							"gid"
			"gml_include_items"						"all"
			"gml_geometries"						"geom"
			"gml_geom_type"							"multiline"
			"gml_verkehrsm_alias"					"verkehrsmittel"
		END

		TYPE LINE

		PROJECTION
			"init=epsg:25832"
		END

		MAXSCALEDENOM 501000
		MINSCALEDENOM 1

		UNITS METERS
		CLASSITEM 'verkehrsm'
		CLASS
			NAME "Bus"
			EXPRESSION 'Bus'
			STYLE
				WIDTH 1.5
				COLOR 0 170 50
				OUTLINECOLOR 255 255 255
				OUTLINEWIDTH 0.5
				LINEJOIN ROUND
			END
		END
		CLASS
			NAME "Straßenbahn"
			EXPRESSION 'Straßenbahn'
			STYLE
				WIDTH 2.2
				COLOR 204 0 0
				OUTLINECOLOR 255 255 255
				OUTLINEWIDTH 0.7
				LINEJOIN ROUND
			END
		END
		CLASS
			NAME "Stadtbahn"
			EXPRESSION 'Stadtbahn'
			STYLE
				WIDTH 3.0
				COLOR 21 106 184
				OUTLINECOLOR 255 255 255
				OUTLINEWIDTH 1
				LINEJOIN ROUND
			END
		END
		CLASS
			NAME "U-Bahn"
			EXPRESSION 'U-Bahn'
			STYLE
				WIDTH 3.0
				COLOR 21 106 184
				OUTLINECOLOR 255 255 255
				OUTLINEWIDTH 1
				LINEJOIN ROUND
			END
		END
	END

	# Gruppenlayer: ÖPNV
	LAYER
		NAME "oepnv"
		METADATA
			"ows_srs"								"EPSG:25832 EPSG:25833 EPSG:3857 EPSG:4258 EPSG:4326 EPSG:31466 EPSG:31467 EPSG:31468 EPSG:31469 EPSG:900913"
			"ows_extent"							"300000.0 5620000.0 440000.0 5770000.0"
			"ows_title"								"ÖPNV"
			"ows_abstract"							"Ebene ÖPNV"
		END
		TYPE POINT
	END

second strange thing:
If I duplicate the "public transportation lines"-layer in the same mapfile (MAPFILE VERSION 2) and change it's name to "NAME "oepnv_linien2" I have a second layer in my service - from that point nothing magic. standard-getlegend against that layer also works well; content dependent legend doesn't produce an error, but just shows the labels in the legend and NOT the legendsymbols... ???

default legend:
spw_web2

content dependent legend (MAPFILE VERSION 2):
spw_web3

content dependent legend - oepnv_linien2 (added to MAPFILE VERSION 2):
spw_web4

**Comment by tbonfort** [comment]
can you (privately) send me the data + full mapfile to reproduce this locally please

**Comment by ruhri** [comment]
Hi Thomas,
send it to 'thomas.bonfort@gmail.com'

Mit freundlichen Grüßen
Im Auftrag

Benjamin Schepers


Luftbild und Geoinformationssysteme
Kronprinzenstraße 35
45128 Essen
Fon: +49 201 2069-232
Fax: +49 201 2069-400
schepers@rvr-online.de

[cid:image001.jpg@01D1486C.A0650D60]

Die Regionaldirektorin
Kronprinzenstraße 35
45128 Essen
Zentrale: +49 (0) 201 2069-0
Fax: +49 (0) 201 2069-500
www.metropoleruhr.de

Postfach 10 32 64
45032 Essen

Steuernummer: RVR 112/5797/0116
USt.-ldNr.: DE 173867500

Diese E-Mail koennte vertrauliche und/oder rechtlich geschuetzte Informationen enthalten.
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtuemlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail sind nicht gestattet.
This e-mail may contain confidential and/or privileged information.
If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail.
Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.
Von: Thomas Bonfort [mailto:notifications@github.com]
Gesendet: Mittwoch, 6. Januar 2016 09:38
An: mapserver/mapserver
Cc: Schepers, Benjamin
Betreff: Re: [mapserver] Content Dependent Legend Rendering Tracking (RFC 101) (#4713)


can you (privately) send me the data + full mapfile to reproduce this locally please

**Comment by tbonfort** [comment]
@ruhri can you try with d02e6fb (applied to branch-7-0)

**Comment by ruhri** [comment]
works well in my scenario, now!!!

THUMBS UP

**Pull request closed without merging**
