### PR TITLE
Collection of backports from the 8.0 development work.

### PR DESCRIPTION
**Pull request by sdlime**
These will contribute increased stability and security. Specifically:

    - https://github.com/MapServer/MapServer/pull/6584  
    - https://github.com/MapServer/MapServer/pull/6577
    - https://github.com/MapServer/MapServer/pull/6458
    - https://github.com/MapServer/MapServer/pull/6466 

Plus fixing (cherrypick) a memory leak discovered while writing OGCAPI tests. 

--Steve

### CODE REVIEW

**Comment by sdlime** [comment]
@jmckenna, is Travis completely hosed for branch-7-6?

**Comment by jmckenna** [comment]
@sdlime the history here is that I put much effort into upgrading TravisCI and GitHub action for MapServer 8.0.0 release (and MapCache 1.14.0 also)....I did not devote time into older branches for either MapServer or MapCache.  If it's required I can find some time, but I was thinking the priorities were the main branches.

**Comment by jmckenna** [comment]
short answer: yes, I would ignore CI errors in older branches for MapServer and MapCache.

**Comment by sdlime** [comment]
> @sdlime the history here is that I put much effort into upgrading TravisCI and GitHub action for MapServer 8.0.0 release (and MapCache 1.14.0 also)....I did not devote time into older branches for either MapServer or MapCache. If it's required I can find some time, but I was thinking the priorities were the main branches.

Oh, I agree with you on priorities. I just wanted to make sure these issues weren't cause by these changes. I don't believe they are...

**Comment by jmckenna** [comment]
Yes, agreed, darn, it was just about priorities.

**Comment by jmckenna** [comment]
Thanks Steve, merging now...

**Pull request merged**
