### PR TITLE
mapscript_csharp compilable on Linux

### PR DESCRIPTION
**Pull request by 3x0dv5**
In reference to
http://osgeo-org.1560.x6.nabble.com/csharp-mapscript-dotnet-core-on-Linux-td5391329.html
and
#5728

##sample usage:
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX=/opt
-DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu:/usr/share/postgresql/10:/usr/local:/opt
-DWITH_CLIENT_WFS=ON
-DWITH_CLIENT_WMS=ON
-DWITH_CURL=ON
-DWITH_SOS=ON
-DWITH_PHP=OFF
-DWITH_PERL=OFF
-DWITH_RUBY=OFF
-DWITH_JAVA=OFF
-DWITH_CSHARP=ON
-DWITH_PYTHON=OFF
-DWITH_SVGCAIRO=OFF
-DWITH_ORACLESPATIAL=OFF
-DWITH_MSSQL2008=OFF
../ >../configure.out.txt
$ make mapscript

### CODE REVIEW

**Comment by geographika** [comment]
@3x0dv5 - excellent!
In order to confirm the C# MapScript builds on Linux (and continues to build for future releases), could you add it to the Travis CI build?

This may/could be as simple as adding the CMAKE flag `-DWITH_CSHARP=1` to the Makefile here:

https://github.com/mapserver/mapserver/blob/418e15cda5109e3a47c6691567e3e3e62e964187/Makefile#L12

In summary Travis is configured with the YAML file at https://github.com/mapserver/mapserver/blob/master/.travis.yml - this in turn calls the Makefile in the `script `section:

```
script:
  - make cmakebuild
  - make mspython-wheel  
  - make -j4 test
```

Appveyor (the Windows CI build) is still completing successfully so that is good news. 
Ideally in the future both Appveyor and Travis would run the sample .NET MapScript applications following the build, but that is outside the scope of this. Thanks for the contribution.

**Comment by 3x0dv5** [comment]
I'll take a look, probably a couple of apt installs will also be required.

**Comment by 3x0dv5** [comment]
@geographika hey by any chance you don't know where are we saying the the lib ".so" is named mapscript.so? 

in `mapscript/csharp/config/mapscript_csharp.dll.config` we have the following:

```xml
<configuration>
    <dllmap dll="mapscript" target="libmapscript.so" />
</configuration>
```
so when we build the examples and we try to run them with mono it fails because internally is going to look for a libmapscript.so and not a mapscript.so.
So we either change the `.config` above to use mapscript.so (and update the docs) or we build a libmapscript.so instead. I don't seem to find where this is being done. (bit tired today)

**Comment by 3x0dv5** [comment]
@geographika what do you think, is this working as expected?

https://travis-ci.com/3x0dv5/mapserver/jobs/170971330

```
export RBENV_ROOT="/home/travis/.phpenv"
exec "/home/travis/.phpenv/libexec/rbenv" exec "$program" "$@"
make[1]: Leaving directory `/home/travis/build/3x0dv5/mapserver'
make[1]: Entering directory `/home/travis/build/3x0dv5/mapserver'
test -d "build/mapscript/csharp" && (export CSHARP_MAPSCRIPT_SO="../../build/mapscript/csharp" && cd mapscript/csharp && ./run_test.sh)
+cd ../../build/mapscript/csharp
+echo .: Testing shpdump.exe :.
.: Testing shpdump.exe :.
+mono shpdump.exe ../../../tests/point.shp
Shape 0 has 1 part(s)
bounds (0, 51.477222) (0, 51.477222)
Part 0 has 1 points.
0: 0, 51.477222
+echo .: Testing drawmap.exe :.
.: Testing drawmap.exe :.
+mono drawmap.exe ../../../tests/test.map ./map.png
# Map layers 7; Map name = Testing
Layer [0] name: RASTER
Layer [1] name: POLYGON
Layer [2] name: LINE
Layer [3] name: POINT
Layer [4] name: INLINE
Layer [5] name: INLINE-PIXMAP-RGBA
Layer [6] name: INLINE-PIXMAP-PCT
Image URL = ; Image path = 
Image height = 200; width = 200
+echo .: Testing shapeinfo.exe :.
.: Testing shapeinfo.exe :.
+mono shapeinfo.exe ../../../tests/point.shp
ShapeType = point
Num shapes = 1
(xmin, ymin) = (0,51.477222) (xmax, ymax) = (0,51.477222)
+echo .: Testing getbytes.exe :.
.: Testing getbytes.exe :.
+mono getbytes.exe ../../../tests/test.map test_csharp2.png
Drawing map: 'Testing' using imageObj.getBytes
Drawing map: 'Testing' using imageObj.write
+echo .: Testing RFC24.exe :.
.: Testing RFC24.exe :.
+mono RFC24.exe ../../../tests/test.map
Running RFC24
	- testLayerObj PASSED
	- testLayerObj refcount PASSED
	- testLayerObjDestroy precondition PASSED
	- testLayerObjDestroy PASSED
	- testClassObj PASSED
	- testClassObj refcount PASSED
	- testClassObjDestroy precondition PASSED
	- testClassObjDestroy PASSED
	- testInsertLayerObj PASSED
	- testInsertLayerObj refcount PASSED
	- testInsertLayerObjDestroy precondition PASSED
	- testInsertLayerObjDestroy PASSED
	- testRemoveLayerObj PASSED
	- testInsertClassObj precondition PASSED
	- testInsertClassObj PASSED
	- testInsertClassObj refcount PASSED
	- testInsertClassObjDestroy precondition PASSED
	- testInsertClassObjDestroy PASSED
	- testRemoveClassObj PASSED
	- testGetLayerObj PASSED
	- testGetLayerObj refcount PASSED
	- testGetLayerObjDestroy precondition PASSED
	- testGetLayerObjDestroy FAILED
	- testGetLayerObjByName PASSED
	- testGetLayerObjByName refcount PASSED
	- testGetLayerObjByNameDestroy precondition PASSED
	- testGetLayerObjByNameDestroy FAILED
	- testGetClassObj PASSED
	- testGetClassObj refcount PASSED
	- testGetClassObjDestroy precondition PASSED
	- testGetClassObjDestroy FAILED
	- testStyleObj PASSED
	- testStyleObjDestroy PASSED
	- testStyleObjDestroy PASSED
	- testInsertStyleObj precondition PASSED
	- testInsertStyleObj PASSED
	- testInsertStyleObjDestroy precondition PASSED
	- testInsertStyleObjDestroy PASSED
	- testRemoveStyleObj PASSED
	- testGetStyleObj PASSED
	- testGetStyleObjDestroy precondition PASSED
	- testGetStyleObjDestroy FAILED
	- testlegendObj PASSED
	- testreferenceMapObj PASSED
	- testwebObj PASSED
	- testqueryMapObj PASSED
	- testmapObjHashTable PASSED
	- testsymbolSetObj PASSED
	- testimageObj PASSED
     4 tests were FAILED!!!
Finished RFC24
make[1]: Leaving directory `/home/travis/build/3x0dv5/mapserver'
The command "make -j4 test" exited with 0.
```

**Comment by geographika** [comment]
@3x0dv5 - yes the Travis build could do with some refactoring. I had a brief look when adding builds/tests for Python2 and Python3 but couldn't see an easy way round running for each PHP config. For now this is fine - and great to see the sample apps and tests running. Please add to the current pull request. 

Do you have a Windows machine setup to see if the same tests are failing on Windows or if it is a mono issue? They all seem to relate to destroying objects. 
I can look at adding a similar test/batch file to Appveyor to run on Windows.

**Comment by 3x0dv5** [comment]
A build from the mapscript_csharp master :) also shows fails in the rfc24. I dont have a windows build machine setup.

http://build2.gisinternals.com/sdk/build-output/vc15x64-20181229-23-47-48-24-vc15x64-stable-2.4-7-2.txt

**Comment by geographika** [comment]
@3x0dv5 - if you are happy with the pull request, I think this can be merged in the next couple of days unless there are any more comments.

**Comment by 3x0dv5** [comment]
I am OK with this, let's see if anyone else has anything to add

**Pull request merged**
