### PR TITLE
update msautotest for new demo server

### PR DESCRIPTION
**Pull request by jmckenna**
- WMS endpoint path on new demo server is now `/mapserver/apps/` which was already configured for `MS_MAP_PATTERN`
- related to https://github.com/MapServer/MapServer/issues/6435

### CODE REVIEW

**Comment by jmckenna** [comment]
@rouault my commits just clashed here, i generated the missing files

**Comment by jmckenna** [comment]
I was working on the server, to generate the 2 missing files.  Could you have waiting 1 minute kindly?

**Comment by jmckenna** [comment]
Apparently not

**Comment by jmckenna** [comment]
Anyway, I think we should not step on toes...this is even my own pull request.  it seems a waste of (unpaid) time

**Comment by jmckenna** [comment]
And i wanted the satisfaction to solve the 'expected' image issues.

**Comment by jmckenna** [comment]
Anyway, thanks for this work @rouault !!!

**Comment by rouault** [comment]
> Could you have waiting 1 minute kindly?

sorry, didn't know you were still working on it. Feel free to revert my modified images if you modified things on the server that affect the expected result.

**Comment by jmckenna** [comment]
Is there an immediate need for this, that you couldn't wait for me to fix my pull request?

**Comment by jmckenna** [comment]
wow

**Comment by jmckenna** [comment]
You must be in a rush.  No worries!  you get the glory.

**Comment by jmckenna** [comment]
thanks again @rouault

**Comment by rouault** [comment]
sorry for the lack of coordination from my part with you.

**Pull request merged**
