### PR TITLE
Fix label point calculation (#5752)

### PR DESCRIPTION
**Pull request by szekerest**

### CODE REVIEW

**Comment by sdlime** [comment]
What is/was the visual impact of this change?

**Comment by szekerest** [comment]
@sdlime If we add multiple newlines to the end of the text, it is misaligned vertically when ANGLE=0
For example:

LABEL
        FONT "arial"
        SIZE 16
        OFFSET 0 0
        POSITION CC
        SHADOWSIZE 1 1
        TEXT "[PropID_0]*[PropID_1]*[PropID_2]*[PropID_3]*[PropID_4]*[PropID_5]*[PropID_6]*[PropID_7]*[PropID_8]"
        WRAP '*'
      END # LABEL

Where the actual values of the properties (ie. PropID_3...PropID_7) are missing. It works properly when ANGLE != 0

**Comment by sdlime** [comment]
+1 then once travis-ci passes... --Steve

**Comment by jmckenna** [comment]
@szekerest can you rebase this against master, instead of branch-7-2 ?

**Comment by rouault** [comment]
Superseded per https://github.com/MapServer/MapServer/pull/6213

**Pull request closed without merging**
