### PR TITLE
Issue 6956

### PR DESCRIPTION
**Pull request by mapcentia**
#6956

### CODE REVIEW

**Comment by mapcentia** [comment]
The second commit should fix the linting check

**Comment by geographika** [comment]
Actually it appears as though the expected output may itself be wrong. The output was modified as part of #6430 - see https://github.com/MapServer/MapServer/commit/3a100ab0ac304700cb16ff12f8a892131b31e89e

The original file looked like this https://github.com/MapServer/MapServer/blob/e2dc1451d22a73ca10f4f930436f2c73e7b496e5/msautotest/sld/expected/map_linemark.png

map_linemark

So this update may actually be fixing a regression.

**Comment by mapcentia** [comment]
I get this now with the linemark.map

image

**Comment by mapcentia** [comment]
Notice: This issue is related to librsvg >= 2.46

**Comment by geographika** [comment]
> I get this now with the linemark.map
> 
> image

Yes this looks to be the original, and correct, output. I've updated the expected results in the branch so we'll see if the tests now pass.

**Pull request merged**
