### PR TITLE
add attribute support for ALIGN and OFFSET in LABEL

### PR DESCRIPTION
**Pull request by danduk82**
This PR adds support of an attribute for the LABEL OFFSET and ALIGN properties, similarly to what is already done for POSITION.

This means that the following is now possible:
```
ALIGN [attribute]
OFFSET [attr_x] [attr_y]
```

I append an archive file [example.tar.gz](https://github.com/mapserver/mapserver/files/4492908/example.tar.gz)  which contains an example SHP file and corresponding mapfile for testing.
For ALIGN, the column in the date must be of type STRING and use one of the following : `"center" | "left" | "right"` as the usual parameters.
For OFFSET, it should be INTEGERS (will be cast to `(int)` anyway).
One can also use `OFFSET 32 [attr]` of course (but I don't see the interest in doing so...)

with the example provided, it is possible to generate something like this:
test

**NB:** my IDE has removed a lot of trailing whitespaces from the files that I have edited (`mapserver.h`, `mapfile.c`, `maputil.c`). If this is a problem I can rework my PR to leave these trailing whitespaces.

### CODE REVIEW

**Comment by geographika** [comment]
@danduk82 looks a nice addition thanks!
Would you be able to add msautotests for the ALIGN and OFFSET bindings?
There are a few [label tests](https://github.com/mapserver/mapserver/blob/master/msautotest/renderers/labels-alignment.map) already that you could base them on.

**Comment by danduk82** [comment]
@geographika , 
OK, I will add a couple of test this afternoon.

**Comment by danduk82** [comment]
@geographika , I am writing the PR for the documentation in `docs` repository, but I don't understand if I have to fill the `en/development/changelog/changelog-7-6.txt` or if it is auto-generated. Shall I point this PR in it or not?

**Comment by jmckenna** [comment]
@danduk82 I update the changelog each release.  Please file your documentation PR in the 'docs' repository in 'branch-7-6'.  We can discuss the doc changes needed there in that docs PR.

**Comment by jmckenna** [comment]
@danduk82 can you take a look at the CI build errors from this build, as well?  It seems 6 tests fail in msautotest:
```
######################################
# sld => sld_text_propertyname_fontsize.png
######################################
compare.im6: improper image header `sld_text_propertyname_fontsize.png' @ error/png.c/ReadPNGImage/3677.

######################################
# sld => sld_text_propertyname_halofill.png
######################################
compare.im6: improper image header `sld_text_propertyname_halofill.png' @ error/png.c/ReadPNGImage/3677.

######################################
# sld => sld_label_function.png
######################################
compare.im6: improper image header `sld_label_function.png' @ error/png.c/ReadPNGImage/3677.

######################################
# sld => sld_text_expression_fontsize.png
######################################
compare.im6: improper image header `sld_text_expression_fontsize.png' @ error/png.c/ReadPNGImage/3677.

######################################
# sld => sld_text_expression_rotation.png
######################################
compare.im6: improper image header `sld_text_expression_rotation.png' @ error/png.c/ReadPNGImage/3677.

######################################
# sld => sld_text_propertyname_rotation.png
######################################
compare.im6: improper image header `sld_text_propertyname_rotation.png' @ error/png.c/ReadPNGImage/3677.

######################################
# sld => sld_text_propertyname_fill.png
######################################
compare.im6: improper image header `sld_text_propertyname_fill.png' @ error/png.c/ReadPNGImage/3677.
```

**Comment by jmckenna** [comment]
@danduk82 will wait for you to fix the build errors, and then release the next RC on Monday (otherwise these changes will have to wait until the next release/release candidate).  thank you again for this contribution!

**Comment by danduk82** [comment]
@jmckenna ,
when I execute the tests locally I have a lot of them failing.
```
Results (30.06s):
     231 passed
     184 failed
```
But when I look at the results I don't see a noticeable difference. I suppose it is some minor binary differences. I am working on Ubuntu 18.04 64bits. Might this be an issue?

I will now check in detail the 6 that you have pointed out to see if I can visually see some problems.

Moreover, I have just added 2 tests for both features, but I don't know if because of the previous statement, now they might be failing as well on your CI?

**Comment by danduk82** [comment]
@jmckenna  no there are indeed some other problems with the 6 tests that you have mentionned, the image is not generated at all

**Comment by danduk82** [comment]
@jmckenna ,
well this is kind of nasty. With my PR, I change the value of `MS_LABEL_BINDING_LENGTH` from 9 to 12 because I have added 3 items in the enum `MS_LABEL_BINDING_ENUM` in `mapserver.h`. With this change, the SLD style parses makes a segfault while reading the style expression in `msSLDParseOgcExpression` (see stacktrace below).
The tests that do not pass are related to SLD layers, and interestingly enough, if I set `MS_LABEL_BINDING_LENGTH=11`, it still works (i.e. the tests are passing).  I have tried to go back to `master` and change only that, and again, if I put `MS_LABEL_BINDING_LENGTH=11` (even without changing the contents of the enum `MS_LABEL_BINDING_ENUM` it still work, but with 12 it crashes.

`labelObj->exprBindings`, which is set to have a dimension of `MS_LABEL_BINDING_LENGTH` (in `mapserver.h`), seems to mess with the macro `LOOP_ON_CHILD_ELEMENT` defined in `mapogcsld.c:495`.

What is strange, is when I use a dimension of  `MS_LABEL_BINDING_LENGTH=12`, the element for which  `msSLDParseOgcExpression` crashes comes with an `objtype` of `MS_OBJ_LABEL` (see code extract below) but I think it should have been `MS_OBJ_STYLE` like almost all the predecessors. I checked one after the other, there are 2 of them that come as `MS_OBJ_LABEL`, and the second is a pointer to an arbitrary memory section, and this is what make the code segfault. 

I struggle a little to understand the complete logic of the code, and I wonder if there is someone that could give me a couple of clarifications here.

I think that I touched some dormant bug by changing `MS_LABEL_BINDING_LENGTH`.

@jmckenna what do you think? If you want to reproduce the bug, I used the mapfiles of the tests, and you can find the `QUERY_STRING` that is used directly at the bottom of this message.

Kind regards,
Andrea

```c
// from msSLDParseOgcExpression in mapogcsld.c:1327
  switch (objtype)
  {
    case MS_OBJ_STYLE:
      lbinding = binding + MS_STYLE_BASE;
      exprBindings = psStyle->exprBindings;
      nexprbindings = &psStyle->nexprbindings;
      break;
    case MS_OBJ_LABEL:
      lbinding = binding + MS_LABEL_BASE;
      exprBindings = psLabel->exprBindings; // this points to something invalid
      nexprbindings = &psLabel->nexprbindings;
      break;
    default:
      return MS_FAILURE;
      break;
  }
```
I noticed that 12 is also the length of `MS_STYLE_BINDING_LENGTH` but I still don't know if this is related.

Anyway, the segfault occurs during the iteration over the 

I run `mapserv -nh QUERY_STRING='map=./msautotest/sld/arithmetic_text.map&SERVICE=WMS&VERSION=1.3&REQUEST=GetMap&CRS=EPSG:4326&BBOX=42,-5,52,9&FORMAT=image/png&WIDTH=200&HEIGHT=200&LAYERS=lline,lpolygon,lpoint&SLD_BODY=<StyledLayerDescriptor version=%221.1.0%22><NamedLayer><Name>lpoint</Name><UserStyle><FeatureTypeStyle><Rule><PointSymbolizer><Graphic><Mark><WellKnownName>star</WellKnownName><Stroke><SvgParameter name=%22stroke%22>#FF0000</SvgParameter><SvgParameter name=%22stroke-opacity%22>1</SvgParameter><SvgParameter name=%22stroke-width%22>1</SvgParameter></Stroke><Fill><SvgParameter name=%22fill%22>#0000FF</SvgParameter><SvgParameter name=%22fill-opacity%22>0.1</SvgParameter></Fill></Mark><Size>20</Size><Rotation>180</Rotation><Displacement><DisplacementX>2</DisplacementX><DisplacementY>2</DisplacementY></Displacement><Opacity>0.5</Opacity></Graphic></PointSymbolizer><TextSymbolizer><Label><PropertyName>name</PropertyName></Label><Font><SvgParameter name=%22font-family%22>vera</SvgParameter><SvgParameter name=%22font-weight%22>bold</SvgParameter><SvgParameter name=%22font-size%22><PropertyName>s12</PropertyName></SvgParameter></Font><Fill><SvgParameter name=%22fill%22>#FFFFFF</SvgParameter></Fill><LabelPlacement><PointPlacement><Displacement><DisplacementX>2</DisplacementX><DisplacementY>20</DisplacementY></Displacement><AnchorPoint><AnchorPointX>0.5</AnchorPointX><AnchorPointY>0.5</AnchorPointY></AnchorPoint><Rotation>15</Rotation></PointPlacement></LabelPlacement><Halo><Radius>2</Radius><Fill><SvgParameter name=%22fill%22>#00FF00</SvgParameter></Fill></Halo></TextSymbolizer></Rule></FeatureTypeStyle></UserStyle></NamedLayer></StyledLayerDescriptor>'`



```gdb
Program received signal SIGSEGV, Segmentation fault.
> backtrace
#0  0x00007ffff728c98d in __GI___libc_free (mem=0x7d2) at malloc.c:3103
#1  0x00007ffff79d1e9f in msFreeExpression (exp=0x5555557b6370) at /home/aborghi/code/mapserver_stuff/mapserver/mapfile.c:1991
#2  0x00007ffff7a02ee2 in msSLDParseOgcExpression (psRoot=0x5555557b3780, psObj=0x5555557b6120, binding=1, objtype=MS_OBJ_LABEL) at /home/aborghi/code/mapserver_stuff/mapserver/mapogcsld.c:1353
#3  0x00007ffff7a0913b in ParseTextPointPlacement (psRoot=0x5555557b3540, psClass=0x5555557b4ae0) at /home/aborghi/code/mapserver_stuff/mapserver/mapogcsld.c:3270
#4  0x00007ffff7a08696 in msSLDParseTextParams (psRoot=0x5555557b30c0, psLayer=0x5555557b3930, psClass=0x5555557b4ae0) at /home/aborghi/code/mapserver_stuff/mapserver/mapogcsld.c:3080
#5  0x00007ffff7a06895 in msSLDParseTextSymbolizer (psRoot=0x5555557b30c0, psLayer=0x5555557b3930, bOtherSymboliser=1, pszUserStyleName=0x0) at /home/aborghi/code/mapserver_stuff/mapserver/mapogcsld.c:2544
#6  0x00007ffff7a02203 in msSLDParseRule (psRoot=0x5555557b2970, psLayer=0x5555557b3930, pszUserStyleName=0x0) at /home/aborghi/code/mapserver_stuff/mapserver/mapogcsld.c:1043
#7  0x00007ffff7a01830 in msSLDParseUserStyle (psUserStyle=0x5555557b2910, psLayer=0x5555557b3930) at /home/aborghi/code/mapserver_stuff/mapserver/mapogcsld.c:790
#8  0x00007ffff7a01add in msSLDParseNamedLayer (psRoot=0x5555557b2880, psLayer=0x5555557b3930) at /home/aborghi/code/mapserver_stuff/mapserver/mapogcsld.c:861
#9  0x00007ffff7a00e2f in msSLDParseSLD (map=0x5555557a7db0, psSLDXML=0x5555557a4f90 "<StyledLayerDescriptor version=\"1.1.0\"><NamedLayer><Name>lpoint</Name><UserStyle><FeatureTypeStyle><Rule><PointSymbolizer><Graphic><Mark><WellKnownName>star</WellKnownName><Stroke><SvgParameter name=\"stroke\">#FF0000</SvgParameter><SvgParameter name=\"stroke-opacity\">1</SvgParameter><SvgParameter name=\"stroke-width\">1</SvgParameter></Stroke><Fill><SvgParameter name=\"fill\">#0000FF</SvgParameter><SvgParameter name=\"fill-opacity\">0.1</SvgParameter></Fill></Mark><Size>20</Size><Rotation>180</Rotation><Displacement><DisplacementX>2</DisplacementX><DisplacementY>2</DisplacementY></Displacement><Opacity>0.5</Opacity></Graphic></PointSymbolizer><TextSymbolizer><Label><PropertyName>name</PropertyName></Label><Font><SvgParameter name=\"font-family\">vera</SvgParameter><SvgParameter name=\"font-weight\">bold</SvgParameter><SvgParameter name=\"font-size\"><PropertyName>s12</PropertyName></SvgParameter></Font><Fill><SvgParameter name=\"fill\">#FFFFFF</SvgParameter></Fill><LabelPlacement><PointPlacement><Displacement><DisplacementX>2</DisplacementX><DisplacementY>20</DisplacementY></Displacement><AnchorPoint><AnchorPointX>0.5</AnchorPointX><AnchorPointY>0.5</AnchorPointY></AnchorPoint><Rotation>15</Rotation></PointPlacement></LabelPlacement><Halo><Radius>2</Radius><Fill><SvgParameter name=\"fill\">#00FF00</SvgParameter></Fill></Halo></TextSymbolizer></Rule></FeatureTypeStyle></UserStyle></NamedLayer></StyledLayerDescriptor>", pnLayers=0x7fffffffd458) at /home/aborghi/code/mapserver_stuff/mapserver/mapogcsld.c:567
#10 0x00007ffff79ff9ee in msSLDApplySLD (map=0x5555557a7db0, psSLDXML=0x5555557a4f90 "<StyledLayerDescriptor version=\"1.1.0\"><NamedLayer><Name>lpoint</Name><UserStyle><FeatureTypeStyle><Rule><PointSymbolizer><Graphic><Mark><WellKnownName>star</WellKnownName><Stroke><SvgParameter name=\"stroke\">#FF0000</SvgParameter><SvgParameter name=\"stroke-opacity\">1</SvgParameter><SvgParameter name=\"stroke-width\">1</SvgParameter></Stroke><Fill><SvgParameter name=\"fill\">#0000FF</SvgParameter><SvgParameter name=\"fill-opacity\">0.1</SvgParameter></Fill></Mark><Size>20</Size><Rotation>180</Rotation><Displacement><DisplacementX>2</DisplacementX><DisplacementY>2</DisplacementY></Displacement><Opacity>0.5</Opacity></Graphic></PointSymbolizer><TextSymbolizer><Label><PropertyName>name</PropertyName></Label><Font><SvgParameter name=\"font-family\">vera</SvgParameter><SvgParameter name=\"font-weight\">bold</SvgParameter><SvgParameter name=\"font-size\"><PropertyName>s12</PropertyName></SvgParameter></Font><Fill><SvgParameter name=\"fill\">#FFFFFF</SvgParameter></Fill><LabelPlacement><PointPlacement><Displacement><DisplacementX>2</DisplacementX><DisplacementY>20</DisplacementY></Displacement><AnchorPoint><AnchorPointX>0.5</AnchorPointX><AnchorPointY>0.5</AnchorPointY></AnchorPoint><Rotation>15</Rotation></PointPlacement></LabelPlacement><Halo><Radius>2</Radius><Fill><SvgParameter name=\"fill\">#00FF00</SvgParameter></Fill></Halo></TextSymbolizer></Rule></FeatureTypeStyle></UserStyle></NamedLayer></StyledLayerDescriptor>", iLayer=-1, pszStyleLayerName=0x0, ppszLayerNames=0x7fffffffd7d8) at /home/aborghi/code/mapserver_stuff/mapserver/mapogcsld.c:183
#11 0x00007ffff78a366a in msWMSLoadGetMapParams(mapObj*, int, char**, char**, int, char const*, char const*, owsRequestObj*) (map=0x5555557a7db0, nVersion=66304, names=0x5555557a0460, values=0x5555557a0790, numentries=11, wms_exception_format=0x0, wms_request=0x5555557a24d0 "GetMap", ows_request=0x7fffffffdc60) at /home/aborghi/code/mapserver_stuff/mapserver/mapwms.cpp:1495
#12 0x00007ffff78b39fb in msWMSDispatch(mapObj*, cgiRequestObj*, owsRequestObj*, int) (map=0x5555557a7db0, req=0x5555557a0420, ows_request=0x7fffffffdc60, force_wms_mode=0) at /home/aborghi/code/mapserver_stuff/mapserver/mapwms.cpp:5019
#13 0x00007ffff78cf7ce in msOWSDispatch (map=0x5555557a7db0, request=0x5555557a0420, ows_mode=-1) at /home/aborghi/code/mapserver_stuff/mapserver/mapows.c:287
#14 0x00007ffff78ddd86 in msCGIDispatchRequest (mapserv=0x5555557a01b0) at /home/aborghi/code/mapserver_stuff/mapserver/mapservutil.c:1708
#15 0x0000555555555717 in main (argc=3, argv=0x7fffffffde58) at /home/aborghi/code/mapserver_stuff/mapserver/mapserv.c:283
```

**Comment by geographika** [comment]
For info the Windows/Appveyor build is failing due to an unrelated missing GDAL dependency - see #6054. The Travis build is not affected by this issue. 
msautotests are not currently run on Appveyor.

**Comment by jmckenna** [comment]
@jbo-ads can you take a look at the above comment from @danduk82 specifically the question of MS_LABEL_BINDING_LENGTH ?

**Comment by jbo-ads** [comment]
@jmckenna, @danduk82: yes I'll work on this. Thank you for the notification.

**Comment by jbo-ads** [comment]
I found the error cause, a stupid oversight while improving SLD on labels. I filed an issue (#6057). I'll pull a fix within minutes.

**Comment by jbo-ads** [comment]
> I found the error cause, a stupid oversight while improving SLD on labels. I filed an issue (#6057). I'll push a fix within minutes.

Done: This is PR danduk82#2

**Comment by jmckenna** [comment]
thanks @jbo-ads

**Comment by danduk82** [comment]
@jbo-ads  thanks!

@jmckenna  shall I wait until [the segfault PR](https://github.com/danduk82/mapserver/pull/2) is merged into master, then rebase and re-submit mine?

**Comment by danduk82** [comment]
@jmckenna  Can you confirm that msautotest is working correctly? 

I still have a lot of binary differences between images on my laptop, but the ones that I have checked seem visually ok.

**Comment by jbo-ads** [comment]
@danduk82 As far as I know, Travis and Appveyor checks include msautotests and both are successful. Binary differences on your side may come from slightly different environments. Do you use Vagrant to run msautotests locally?

**Comment by danduk82** [comment]
@jbo-ads I am running the tests locally. So this might be the issue.

**Comment by danduk82** [comment]
@jmckenna , I was wondering if you think that this PR is now in a green state for merging? Or shall I do something more?

**Comment by jmckenna** [comment]
@danduk82 thanks, this was on my list today, merging now...  Thank you again for all of this effort!

**Comment by danduk82** [comment]
@jmckenna  thanks a lot. It was very interesting to dive into mapserver, and I hope I will have more occasions to contribute in the future.

**Comment by jmckenna** [comment]
@danduk82 the automatic creation of a PR for branch-7-6 for these changes failed for some reason; can you please generate one today for these changes?

**Comment by danduk82** [comment]
@jmckenna , if I try to rebase my branch on 7.6 I get a lot of things that want to pass into:

**Comment by danduk82** [comment]
and from what I see, there is a conflict in the SLD module because of the fix of the segfault.

**Comment by danduk82** [comment]
@jmckenna  I suggest that we keep further discussion in the new PR: https://github.com/mapserver/mapserver/pull/6059

**Pull request merged**
