### PR TITLE
Issue 5724 - Skip Failures Processing Option for OGR Driver

### PR DESCRIPTION
**Pull request by sdlime**
See #5724 for more information.

### CODE REVIEW

**Comment by sdlime** [comment]
Reminder: need to squash before merging...

**Comment by rouault** [comment]
That's reasonable. But a simpler patch would be to not call at all CPLGetLastErrorType(). Most GDAL code that iterates over features just rely on GetNextFeature() == NULL to stop iterations.

**Comment by sdlime** [comment]
> That's reasonable. But a simpler patch would be to not call at all CPLGetLastErrorType(). Most GDAL code that iterates over features just rely on GetNextFeature() == NULL to stop iterations.

Do think it would be easier to start over or edit the patch?

**Comment by rouault** [comment]
> Do think it would be easier to start over or edit the patch?

perhaps start over

**Comment by sdlime** [comment]
Closing. Will update #5724 with notes... --Steve

**Pull request closed without merging**
