### PR TITLE
FLTGetBinaryComparisonCommonExpression(): escape date literals with b…

### PR DESCRIPTION
**Pull request by rouault**
…ackquote (#5104)

### CODE REVIEW

**Comment by rouault** [comment]
@sdlime Does that look good to you ?

**Comment by sdlime** [comment]
Yes, I think so. I was wondering if this might be the case. Perhaps I was a bit overzealous when I removed some driver-specific code from mapogcfiltercommon.c. --Steve

**Comment by rouault** [comment]
@sdlime Not sure what the policy is regarding branches : after committing into branch-7-0, should I "git merge branch-7-0" into master ?

**Comment by sdlime** [comment]
You're way better at git than I... ;-) Can you just cherry pick this modification without merging the whole branch?

**Pull request merged**
