### PR TITLE
compile the Ms sql plugin

### PR DESCRIPTION
**Pull request by lepirlouit**

### CODE REVIEW

**Comment by jmckenna** [comment]
@lepirlouit I have never faced this issue (using MSVC 2012).  What compiler are you using?

**Comment by geographika** [comment]
Is the windows.h file there to make it clear the plugin can only be compiled on Windows?

**Comment by lepirlouit** [comment]
why can the plugin not be compiled on linux ?

**Comment by geographika** [comment]
@lepirlouit - this has been fixed with #5996, and the MSSQL driver is now built on Travis/Linux as part of the MapServer CI tests. Thanks for raising this.

**Pull request closed without merging**
