### PR TITLE
PostGIS: use ST_Intersects instead of && for bounding box (fixes #6181, fixes #6230)

### LINKED ISSUE #6181: WFS 2.0 paging problem with Postgis and BBOX
MapServer ver 7.6.1

Mapserver requests features from Postgis with a query similar to this:
```
select "id"::text,ST_AsText("geometry") as geom,"id"::text from table
where 
"geometry" && ST_GeomFromText('POLYGON((415885.464144915 4936233.565163,415885.464144915 4938751.56294925,419080.0342134 4938751.56294925,419080.0342134 4936233.565163,415885.464144915 4936233.565163))',32632) 
limit 1001 offset 2000;
```
The use of **&&** for better performace will only checking if the **bounding boxes of geometry intersects**.
[docs/overlaps_geometry_box2df.html](https://postgis.net/docs/overlaps_geometry_box2df.html)

In the file [mapquery.c#L1252](https://github.com/MapServer/MapServer/blob/9bd402c3596c252195da90a487961b12a15f34c6/mapquery.c#L1252)
a more restrictive check is then performed, for exmple **msIntersectPolygons** 
which in same case can exclude some geometries returned from db breaking the paging mechanism.

In the images you can see a case of a geometry returned by Postgis but excluded from Mapserver check, 
which breaks the feature count for the pagination calculation.

immagine

immagine

### LINKED ISSUE #6230: Wrong number of result when we use a limit
## Expected behavior and actual behavior.

When I do a WFS GetFeature request on 2 layers with a limit some times the number of results is lower than expected.

It's like that MapServer query the first layer, and if he is OK with the number of getting features, event if it didn't raise the limit, he didn't query the second layer...

## Steps to reproduce the problem.

The following request
```
curl 'https://localhost:8484/' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: fr-CH,fr;q=0.8,en;q=0.5,en-US;q=0.3' --compressed -H 'Referer: https://localhost:8484/' -H 'Content-Type: text/xml; charset=UTF-8' -H 'Origin: https://localhost:8484' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cookie: cookieconsent_status=deny; ga-disable-UA-2577926-1=true; _osm_location=6.8753%7C46.1924%7C16%7CM; _LOCALE_=fr; JSESSIONID=65435F16F81E6AE673702C33B9E31C6D; GS_FLOW_CONTROL=GS_CFLOW_753d283f:171d1813121:-7ffe; _osm_session=efe18880ebe449c0fc9392646df71daa' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw '<GetFeature xmlns="http://www.opengis.net/wfs" service="WFS" version="1.1.0" outputFormat="GML3" maxFeatures="5" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Query typeName="feature:fuel" srsName="EPSG:2056" xmlns:feature="http://mapserver.gis.umn.edu/mapserver"><Filter xmlns="http://www.opengis.net/ogc"><BBOX><PropertyName>geom</PropertyName><Envelope xmlns="http://www.opengis.net/gml" srsName="EPSG:2056"><lowerCorner>2607162.692786508 1184272.6393956193</lowerCorner><upperCorner>2612615.91629499 1190100.5118474325</upperCorner></Envelope></BBOX></Filter></Query><Query typeName="feature:post_office" srsName="EPSG:2056" xmlns:feature="http://mapserver.gis.umn.edu/mapserver"><Filter xmlns="http://www.opengis.net/ogc"><BBOX><PropertyName>geom</PropertyName><Envelope xmlns="http://www.opengis.net/gml" srsName="EPSG:2056"><lowerCorner>2607162.692786508 1184272.6393956193</lowerCorner><upperCorner>2612615.91629499 1190100.5118474325</upperCorner></Envelope></BBOX></Filter></Query></GetFeature>'
```

Returns me 3 results on MapServer 7.6 but 5 on MapServer 7.4.

Layers definition:
```
LAYER
    NAME "post_office"
    EXTENT 2473743 1074095 2839000 1306400
    TYPE POINT
    STATUS ON
    TEMPLATE fooOnlyForWMSGetFeatureInfo # For GetFeatureInfo
    CONNECTIONTYPE postgis
    PROCESSING "CLOSE_CONNECTION=DEFER" # For performance
    CONNECTION "host=${PGHOST_SLAVE} port=${PGPORT_SLAVE} user=${PGUSER} password=${PGPASSWORD} dbname=${OSM_PGDATABASE}"
    DATA "geom FROM (
        SELECT
            regexp_replace(format(\'%s\', name), \'^$\', osm_id::text) AS display_name,
            name,osm_id,access,aerialway,amenity,barrier,bicycle,brand,building,covered,denomination,ele,foot,highway,
            layer,leisure,man_made,motorcar,\"natural\", operator, population, power, place, railway, ref, religion,
            shop, sport, surface, tourism, waterway, wood, way AS geom
        FROM planet_osm_point
        WHERE amenity = 'post_office'
    ) AS foo USING unique osm_id USING srid=2056"
    LABELITEM "name"
    PROJECTION
        "init=epsg:2056"
    END
    TOLERANCE 10
    TOLERANCEUNITS pixels

    CLASS
        NAME "Office de poste"
        KEYIMAGE symbols/postal.png
        STYLE
            SYMBOL "postal"
            SIZE 30
        END
        LABEL
            SIZE 12
            OFFSET 0 10
            COLOR 128 128 0
            OUTLINECOLOR 255 255 255
            OUTLINEWIDTH 2
            PARTIALS FALSE
            MAXSCALEDENOM 150000
        END
    END
    METADATA
        "wms_title" "post_office"
        "gml_include_items" "all"
        "gml_types" "auto"
        "gml_featureid" "osm_id"
        "gml_geom_type" "point"
        "gml_geometries" "geom"
    END
END

LAYER
    NAME "fuel"
    EXTENT 2473743 1074095 2839000 1306400
    TYPE POINT
    STATUS ON
    TEMPLATE fooOnlyForWMSGetFeatureInfo # For GetFeatureInfo
    CONNECTIONTYPE postgis
    PROCESSING "CLOSE_CONNECTION=DEFER" # For performance
    CONNECTION "host=${PGHOST_SLAVE} port=${PGPORT_SLAVE} user=${PGUSER} password=${PGPASSWORD} dbname=${OSM_PGDATABASE}"
    DATA "geom FROM (
        SELECT
            regexp_replace(format(\'%s\', name), \'^$\', osm_id::text) AS display_name,
            name,osm_id,access,aerialway,amenity,barrier,bicycle,brand,building,covered,denomination,ele,
            foot,highway,layer,leisure,man_made,motorcar,\"natural\", operator, population, power, place,
            railway, ref, religion, shop, sport, surface, tourism, waterway, wood, way AS geom
        FROM planet_osm_point
        WHERE amenity = 'fuel'
    ) AS foo USING unique osm_id USING srid=2056"
    LABELITEM "name"
    PROJECTION
        "init=epsg:2056"
    END
    TOLERANCE 10
    TOLERANCEUNITS pixels

    CLASS
        NAME "Station service"
        KEYIMAGE symbols/fillingstation.png
        STYLE
            SYMBOL "fillingstation"
            SIZE 30
        END
        LABEL
            SIZE 12
            OFFSET 0 10
            COLOR 157 112 80
            OUTLINECOLOR 255 255 255
            OUTLINEWIDTH 2
            PARTIALS FALSE
            MAXSCALEDENOM 150000
        END
    END
    METADATA
        "wms_title" "fuel"
        "gml_include_items" "all"
        "gml_types" "auto"
        "gml_featureid" "osm_id"
        "gml_geom_type" "point"
        "gml_geometries" "geom"
    END
END
```

## Operating system

Ubuntu 20.04 64 bit

## MapServer version and installation method

7.6.2

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by sdlime** [comment]
I'm not positive on this but I was trying branch-7-6 in production and ran into some weirdness with mode=nquery and PostGIS layers. I was doing point queries on polygon layers and experiencing inconsistent results across multiple layers - some features would return as a result and some wouldn't. Reverting to the 7.6.3 release fixed things. This looks to be the only addition that could affect those operations but it's not obvious to me why. I'll have to try and narrow it down. Is there anything that might be specific to PostGIS version with this change?

--Steve

**Comment by rouault** [comment]
I'm not aware of PostGIS version making a difference for ST_Intersection(), but one thing I noticed is that ST_Intersection() was more picky about SRID than &&. I had to do https://github.com/MapServer/MapServer/blob/main/mappostgis.cpp#L1824 because of that

**Comment by sdlime** [comment]
I'll try and put together a simple test case. I do have a repeatable example where with 7.6.3 things work as expected but fail with the current 7.6 branch. I need to simplify it...

**Comment by sdlime** [comment]
Hi Even: Back at this and with debugging on with point queries the SQL that gets generated looks something like:

```
select "objectid"::text,"dowlknum"::text,"lake_name"::text,"lakefinder"::text,ST_AsBinary(("shape"),'NDR') as geom,"objectid"::text from (SELECT shape, objectid, dowlknum, map_label AS lake_name, in_lakefinder AS lakefinder FROM gdrs.dnr_hydro
_features_compass WHERE map_display='Y' AND map_label != '') as foo where ST_Intersects("shape", ST_GeomFromText('POLYGON((440050.852933846 5129741.71595332,440050.852933846 5129741.71595332,440050.852933846 5129741.71595332,440050.852933846 5129741.71595332,440050.852933846 5129741.71595332))',26915))
```

The bounding box is actually just a point in these cases (xmin=xmax, ymin=ymax) which never caused problems. In this case the  resulting POLYGON has the same issue where all points in the geometry are the same. The ST_Intersects() function seems to be indeterminate in this case - sometimes it works, sometimes it doesn't. 

If I edit the SQL and turn the POLYGON into a POINT, so:

```
select "objectid"::text,"dowlknum"::text,"lake_name"::text,"lakefinder"::text,ST_AsBinary(("shape"),'NDR') as geom,"objectid"::text from 
(SELECT shape, objectid, dowlknum, map_label AS lake_name, in_lakefinder AS lakefinder FROM gdrs.dnr_hydro_features_compass WHERE map_display='Y' AND map_label != '') as foo 
where ST_Intersects("shape", ST_GeomFromText('POINT(440050.852933846 5129741.71595332)',26915))
```

then the correct feature is found.

--Steve

**Comment by rouault** [comment]
> Hi Even: Back at this and with debugging on with point queries the SQL that gets generated looks something like:

should be fixed per https://github.com/MapServer/MapServer/pull/6354

**Pull request merged**
