### PR TITLE
Fix memory leaks in mapdrawgdal.c

### PR DESCRIPTION
**Pull request by gogglesguy**
1. To prevent mask_rb from leaking, it now gets allocated on the stack.
2. hColorMap wasn't always freed in case there was an error.
3. Several other minor leaks that didn't get freed on error.

### CODE REVIEW

**Comment by rouault** [comment]
cherry picked into master as 51bd4d78f0b57deac8b714375051f5398de1f41e

**Comment by gogglesguy** [comment]
Why did you git cherrypick instead of git merge into master? Considering this is a bug/hot fix on the release branch, a merge should have just worked fine. (See http://nvie.com/posts/a-successful-git-branching-model/#hotfix-branches)

**Comment by rouault** [comment]
> Why did you git cherrypick instead of git merge into master? Considering this is a bug/hot fix on the release branch, a merge should have just worked fine. (See http://nvie.com/posts/a-successful-git-branching-model/#hotfix-branches)

It is just I'm a really basic git user, and I feel more confident in cherry picking rather than merging, because I find it hard for the latter to exactly know what I'm pulling.

**Comment by gogglesguy** [comment]
I'm by no means a git expert, but there are downsides to cherrypicking, see for example: http://www.draconianoverlord.com/2013/09/07/no-cherry-picking.html
(once you start merging branches with identical commits, it becomes a real pain). That said, I found the "successful Git branching model" link from earier comment easy to work with.

Anyway, do you want me to continue posting bugfixes/memory leaks from branch-7.0 or switch to master. I still need these changes myself in 7.0...

**Comment by rouault** [comment]
@sdlime @tbonfort any opinion on the appropriate procedure for the above ?

@gogglesguy  Regarding committing to branch-7-0 I'm personaly rather conservative on that., especially when I'm not the author of the changes See my email https://lists.osgeo.org/pipermail/mapserver-dev/2015-August/014575.html . Other committers might have different feelings.

**Comment by tbonfort** [comment]
closing. @gogglesguy fixes/pull-requests on branch-7-0 are fine/preferred. pull-requests directly on master would only be for changes that should not go into the stable releases (i.e. new functionality or breaking backwards compatibility)

**Pull request closed without merging**
