### PR TITLE
MS_LEGEND_KEYSIZE_MAX to 1000

### PR DESCRIPTION
**Pull request by gu-LGB**
See issue 7152:
https://github.com/MapServer/MapServer/issues/7152

### CODE REVIEW

**Comment by gu-LGB** [comment]
The [documentation ](https://mapserver.org/mapfile/legend.html#mapfile-legend-keysize) still needs to be adjusted. However, I couldn't find it in the repo.

Is it possible to make the change retroactive to mapserver 8.2?

**Comment by jmckenna** [comment]
@gu-LGB you can file a documentation change through a pull request in its repository at https://github.com/MapServer/MapServer-documentation/pulls

**Comment by geographika** [comment]
@jmckenna - I think this is fine to backport to the 8.2 and 8.0 branches

**Comment by jmckenna** [comment]
@geographika thanks, I agree, that was my plan (I only was hesitant to proceed before as there is no msautotest case, but, merging now...)

**Pull request merged**
