### PR TITLE
Updates to build MapScript with SWIG 4.0.1

### PR DESCRIPTION
**Pull request by geographika**
See issue #5982

- Python test suite now passes when built with SWIG 4.0.1 with this pull request. 
- Appveyor checks Python with both SWIG 3.0.12 (in the x32 build) and SWIG 4.0.1
- C# binding code commented out to successfully build, but I'm unsure if there are any unwanted side-effects
- PHP and Perl are built and tested on Travis so this will need updating to check these are working

### CODE REVIEW

**Comment by geographika** [comment]
@szekerest - I've added a conditional statement to only remove the existing C# typemaps which cause SWIG 4 to fail when building with < SWIG 4. You may know better if these can be removed completely. 

@jmckenna reported on the mailing list that the PHP MapScript has been building successfully on SWIG 4 for sometime as part of ms4w. @tigerfoot @sebastic if you get a chance to review please let me know if these changes could cause any openSUSE / Ubuntu build problems. 

The Travis build currently uses SWIG 3.0.12 and all tests are passing so these updates at least are SWIG 3 compatible.

**Comment by tigerfoot** [comment]
@geographika I've made a backport to 7.4.3 for python, and the build work nicely now so +1 on my side
( Can't test C# ) but java,perl,php,python mapscript modules are all build (with 7.4.3 + patches version)

**Comment by rouault** [comment]
This needs to be rebased on latest master due to a conflict in bug_check.py

**Comment by geographika** [comment]
@rouault - I've updated to the latest master (a rebase via TortoiseGit, not sure why the commits are showing up twice, but this pull request can be squashed). 
The `test_pattern` is a Python MapScript related test so I've moved to the MapScript test suite rather than part of msautotest. 
If you are happy with this I can merge?

**Comment by rouault** [comment]
Looks good to me

**Pull request merged**
