### PR TITLE
FlatGeobuf: Bugfix feature access

### PR DESCRIPTION
**Pull request by bjornharrtell**
Attempt to reproduce issue #6550.

### CODE REVIEW

**Comment by bjornharrtell** [comment]
But I'm unable to get feature attributes out.. get feature response only contains geometry and I'm failing to understand what I'm doing wrong. Looks like this locally:

Command line:

/home/bjorn/code/MapServer/build/mapserv "QUERY_STRING=map=/home/bjorn/code/MapServer/msautotest/misc/flatgeobuf.map&SERVICE=WFS&REQUEST=getfeature&VERSION=2.0.0&TYPENAMES=africa-continent&COUNT=1"

Response:

```xml
<?xml version='1.0' encoding="UTF-8" ?>
<wfs:FeatureCollection
   xmlns:ms="http://mapserver.gis.umn.edu/mapserver"
   xmlns:gml="http://www.opengis.net/gml/3.2"
   xmlns:wfs="http://www.opengis.net/wfs/2.0"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://mapserver.gis.umn.edu/mapserver https://localhost/wfs?SERVICE=WFS&amp;VERSION=2.0.0&amp;REQUEST=DescribeFeatureType&amp;TYPENAME=africa-continent&amp;OUTPUTFORMAT=application%2Fgml%2Bxml%3B%20version%3D3.2 http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd"
   timeStamp="2022-07-03T20:46:58" numberMatched="unknown" numberReturned="1"
   next="https://localhost/wfs?SERVICE=WFS&amp;REQUEST=getfeature&amp;VERSION=2.0.0&amp;TYPENAMES=africa-continent&amp;COUNT=1&amp;STARTINDEX=1">
      <wfs:boundedBy>
      	<gml:Envelope srsName="urn:ogc:def:crs:EPSG::4326">
      		<gml:lowerCorner>-1.000000 -1.000000</gml:lowerCorner>
      		<gml:upperCorner>-1.000000 -1.000000</gml:upperCorner>
      	</gml:Envelope>
      </wfs:boundedBy>
<!-- WARNING: No featureid defined for typename 'africa-continent'. Output will not validate. -->
    <wfs:member>
      <ms:africa-continent>
        <gml:boundedBy>
        	<gml:Envelope srsName="urn:ogc:def:crs:EPSG::4326">
        		<gml:lowerCorner>-1.000000 -1.000000</gml:lowerCorner>
        		<gml:upperCorner>-1.000000 -1.000000</gml:upperCorner>
        	</gml:Envelope>
        </gml:boundedBy>
        <ms:msGeometry>
          <gml:Polygon gml:id=".1" srsName="urn:ogc:def:crs:EPSG::4326">
            <gml:exterior>
              <gml:LinearRing>
                <gml:posList srsDimension="2">-12.469833 49.543519 -12.895285 49.808981 -13.555761 50.056511 -14.758789 50.217431 -15.226512 50.476537 -15.706069 50.377111 -16.000263 50.200275 -15.414253 49.860606 -15.710204 49.672607 -16.451037 49.863344 -16.875042 49.774564 -17.106036 49.498612 -17.953064 49.435619 -19.118781 49.041792 -20.496888 48.548541 -22.391501 47.930749 -23.781959 47.547723 -24.941630 47.095761 -25.178463 46.282478 -25.601434 45.409508 -25.346101 44.833574 -24.988345 44.039720 -24.460677 43.763768 -23.574116 43.697778 -22.776904 43.345654 -22.057413 43.254187 -21.336475 43.433298 -21.163307 43.893683 -20.830459 43.896370 -20.072366 44.374325 -19.435454 44.464397 -18.961995 44.232422 -18.331387 44.042976 -17.409945 43.963084 -16.850496 44.312469 -16.216219 44.446517 -16.179374 44.944937 -15.974373 45.502732 -15.793454 45.872994 -15.780018 46.312243 -15.210182 46.882183 -14.594303 47.705130 -14.091233 48.005215 -13.663869 47.869047 -13.784068 48.293828 -13.089175 48.845060 -12.487868 48.863509 -12.040557 49.194651 -12.469833 49.543519 </gml:posList>
              </gml:LinearRing>
            </gml:exterior>
          </gml:Polygon>
        </ms:msGeometry>
      </ms:africa-continent>
    </wfs:member>
</wfs:FeatureCollection>
```

**Comment by rouault** [comment]
Perhaps relevant issue raised by Coverity Scan:
```
static void msFGBPassThroughFieldDefinitions(layerObj *layer, flatgeobuf_ctx *ctx)
 43{
   1. Condition i < ctx->columns_len, taking true branch.
 44  for (int i = 0; i < ctx->columns_len; i++) {
   2. var_decl: Declaring variable item without initializer.
 45    char item[16];
 46    //int  nWidth=0, nPrecision=0;
 47    char gml_width[32], gml_precision[32];
 48    const char *gml_type = NULL;
 49
 50    flatgeobuf_column column = ctx->columns[i];
 51
 52    gml_width[0] = '\0';
 53    gml_precision[0] = '\0';
 54
   3. Switch case value 0.
 55    switch( column.type ) {
 56      case flatgeobuf_column_type_byte:
 57      case flatgeobuf_column_type_ubyte:
 58      case flatgeobuf_column_type_bool:
 59      case flatgeobuf_column_type_short:
 60      case flatgeobuf_column_type_ushort:
 61      case flatgeobuf_column_type_int:
 62      case flatgeobuf_column_type_uint:
 63        gml_type = "Integer";
 64        //sprintf( gml_width, "%d", nWidth );
   4. Breaking from switch.
 65        break;
 66      case flatgeobuf_column_type_long:
 67      case flatgeobuf_column_type_ulong:
 68        gml_type = "Long";
 69        //sprintf( gml_width, "%d", nWidth );
 70        break;
 71      case flatgeobuf_column_type_float:
 72      case flatgeobuf_column_type_double:
 73        gml_type = "Real";
 74        //sprintf( gml_width, "%d", nWidth );
 75        //sprintf( gml_precision, "%d", nPrecision );
 76        break;
 77      case flatgeobuf_column_type_string:
 78      case flatgeobuf_column_type_json:
 79      case flatgeobuf_column_type_datetime:
 80      default:
 81        gml_type = "Character";
 82        //sprintf( gml_width, "%d", nWidth );
 83        break;
 84    }
 85
   CID 1518687 (#1 of 1): Uninitialized scalar variable (UNINIT)5. uninit_use_in_call: Using uninitialized value *item when calling msUpdateGMLFieldMetadata. [[show details](https://scan7.scan.coverity.com/eventId=18441919-6&modelId=18441919-0&fileInstanceId=122082576&filePath=%2Fmapows.c&fileStart=1215&fileEnd=1241)]
 86    msUpdateGMLFieldMetadata(layer, item, gml_type, gml_width, gml_precision, 0);
 87  }
 88}
```

**Comment by bjornharrtell** [comment]
@rouault doesn't appear to be the cause, I've added some guesses to the metadata now and still get nothing out. I'm unsure what  would be correct width for integer types.

**Comment by bjornharrtell** [comment]
There is something I am simply overlooking in how to get WFS with attributes to work... can't get anything out when doing the same thing against africa.shp.

**Comment by jmckenna** [comment]
@bjornharrtell next deadline is this Friday, for any changes to make it in the next beta (or the first official/public beta, ha).

Can I help in this ticket?  I could, for example, add the necessary WFS (and outputformat) settings into the existing msautotest mapfile (which will fail, but will make it easy for you to tackle).  Is that a good plan of attack?

**Comment by jmckenna** [comment]
ah, this Pull Request already does update that mapfile! (sorry I'm slow, ha).  Mind if I modify?

**Comment by rouault** [comment]
@bjornharrtell I've had a look at this. I applied this PR as well as https://github.com/MapServer/MapServer/pull/6552, and added a few traces. The error is that msFlatGeobufLayerGetShape() calls flatgeobuf_read_feature_offset() with a likely wrong offset, which cause a funky featureSize to be requested. See output of your WFS requests with the following added debug traces:
```
diff --git a/flatgeobuf/flatgeobuf_c.cpp b/flatgeobuf/flatgeobuf_c.cpp
index c959cc6c3..0b7c003dc 100644
--- a/flatgeobuf/flatgeobuf_c.cpp
+++ b/flatgeobuf/flatgeobuf_c.cpp
@@ -96,6 +96,7 @@ int flatgeobuf_decode_feature(ctx *ctx, layerObj *layer, shapeObj *shape)
         }
         return -1;
     }
+    fprintf(stderr, "featureSize = %u\n", featureSize);
diff --git a/mapflatgeobuf.c b/mapflatgeobuf.c
index 1dbc1c49b..f8904e2a6 100644
--- a/mapflatgeobuf.c
+++ b/mapflatgeobuf.c
 @@ -244,6 +244,7 @@ int msFlatGeobufLayerGetShape(layerObj *layer, shapeObj *shape, resultObj *recor
   long i = record->shapeindex;
   uint64_t offset;
   flatgeobuf_read_feature_offset(ctx, i, &offset);
+    fprintf(stderr, "next_shape: %d %d\n", ctx->feature_offset, offset);
   if (VSIFSeekL(ctx->file, ctx->feature_offset + offset, SEEK_SET) == -1) {
       msSetError(MS_FGBERR, "Unable to seek in file", "msFlatGeobufLayerGetShape");
       return MS_FAILURE;

```

output:
```
next_shape: 3344 53
featureSize = 1633907553
```

**Comment by jmckenna** [comment]
@bjornharrtell I've also updated the `flatgeobuf.map' for proper WFS output (the same mapfile with an equivalent 'africa.shp' format serves the geometry and attributes ; as FGB it does not serve geometry or attributes).

**Review by jmckenna — CHANGES_REQUESTED** [review]
@bjornharrtell I had already added the appropriate metadata object through https://github.com/MapServer/MapServer/pull/6553/commits/4dc52c20513a5000b64e89faa7d709a7455f211d Your change here adds a second metadata object in the same layer?  I think your change here should be removed.

**Comment by bjornharrtell** [comment]
Aha! msFlatGeobufLayerGetShape is called even without bbox filer and indes search.. and request shapeindex -1, just as was initially reported. I don't understand the logic of that... and to me it looks like that is an error condition in mapshape.c too... searching for answers.

**Review by jmckenna — APPROVED** [review]

**Comment by jmckenna** [comment]
@bjornharrtell with your latest changes, the compile fails locally here on Windows with:
````
flatgeobuf\flatgeobuf_c.cpp(142): warning C4244: 'initializing': conversion from 'int' to 'uint16_t', possible loss of data
flatgeobuf\flatgeobuf_c.cpp(173): warning C4244: 'argument': conversion from 'int32_t' to 'uint16_t', possible loss of data
flatgeobuf\flatgeobuf_c.cpp(176): warning C4244: 'argument': conversion from 'int32_t' to 'uint16_t', possible loss of data
flatgeobuf\flatgeobuf_c.cpp(179): warning C4244: 'argument': conversion from 'int32_t' to 'uint16_t', possible loss of data
flatgeobuf\flatgeobuf_c.cpp(182): warning C4244: 'argument': conversion from 'int32_t' to 'uint16_t', possible loss of data
flatgeobuf\flatgeobuf_c.cpp(185): warning C4244: 'argument': conversion from 'int32_t' to 'uint16_t', possible loss of data
flatgeobuf\flatgeobuf_c.cpp(188): warning C4244: 'argument': conversion from 'int32_t' to 'uint16_t', possible loss of data
flatgeobuf\flatgeobuf_c.cpp(191): warning C4244: 'argument': conversion from 'int32_t' to 'uint16_t', possible loss of data
flatgeobuf\flatgeobuf_c.cpp(194): warning C4244: 'argument': conversion from 'int32_t' to 'uint16_t', possible loss of data
flatgeobuf\flatgeobuf_c.cpp(197): warning C4244: 'argument': conversion from 'int32_t' to 'uint16_t', possible loss of data
flatgeobuf\flatgeobuf_c.cpp(200): warning C4244: 'argument': conversion from 'int32_t' to 'uint16_t', possible loss of data
flatgeobuf\flatgeobuf_c.cpp(203): warning C4244: 'argument': conversion from 'int32_t' to 'uint16_t', possible loss of data
flatgeobuf\flatgeobuf_c.cpp(235): error C2131: expression did not evaluate to a constant
flatgeobuf\flatgeobuf_c.cpp(235): note: failure was caused by non-constant arguments or reference to a non-constant symbol
flatgeobuf\flatgeobuf_c.cpp(235): note: see usage of 'FLATGEOBUF_MAGICBYTES_SIZE'
flatgeobuf\flatgeobuf_c.cpp(241): warning C4018: '<': signed/unsigned mismatch
flatgeobuf\flatgeobuf_c.cpp(304): warning C4244: '=': conversion from 'mapserver::flatbuffers::uoffset_t' to 'uint16_t', possible loss of data
````

**Comment by bjornharrtell** [comment]
With the fixes here I can get basic WFS access to work. There was multiple issues with the logic.

**Pull request merged**
