### PR TITLE
Change legend symbol scale factor when SIZEUNITS is set to METERS

### PR DESCRIPTION
**Pull request by PatrikSylve**
When SIZEUNITS METERS is set in LAYER, the symbol won't show in the legend. This is due to that the scale factor will get the value INFINTY.

Related issue: 
https://github.com/mapserver/mapserver/issues/5096

### CODE REVIEW

**Comment by sdlime** [comment]
Would a better test be when layer size units is not given in pixels?

**Comment by jmckenna** [comment]
@PatrikSylve if these tests pass we can include this in today's 7.6.4 release.

**Comment by PatrikSylve** [comment]
> @PatrikSylve if these tests pass we can include this in today's 7.6.4 release.

Seems like the PDF image is still not passing the test here. 

I had some issues with running the tests on my machine so I used the following command to generate the expected images:
> ./mapserv -nh "QUERY_STRING=map=/home/patriksylve/code/MapServer/msautotest/renderers/legend_sizeunits_meters.map&mode=legend&map.imagetype=pdf" >> img/legend_sizeunits_meters.pdf 

The results look fine to me. Could it maybe be caused by differing dependency versions or something like that?

**Comment by jmckenna** [comment]
@PatrikSylve I understand your frustration - I've now setup your branch locally on Windows here and 3 tests fail here for `legend_sizeunits_meters.map` (the non-cairo PNG, and the PDF & SVG.  (I can see one-digit precision differences in the SVG numbers)  Hmmmmmmm.....

**Comment by PatrikSylve** [comment]
@jmckenna Hm ok. That is strange.  

I managed to get the tests running on my linux now, and it now says that all 4 tests passed. I tried compiling mapserver on another linux as well and got the same result. 

However, when i run local tests on legend.map the PDF-format fails, but the resulting legend.pdf has the same hash as the legend_sizeunits_meters.pdf. So I will try to commit the legend.pdf but renamed as legend_sixeuntis_meters.map. Hopefully the test will pass now.

**Comment by PatrikSylve** [comment]
Seems like it was different versions of cairo that caused the problem: 
pdf_diff

**Comment by jmckenna** [comment]
Thanks for all of this effort @PatrikSylve !  (you're likely right, caused by Cairo version differences)

**Comment by jmckenna** [comment]
This has been backported to branch-7-6 manually

**Pull request merged**
