### PR TITLE
Fixed case when drawing legend shapes with style geomtransforms. (#5193)

### PR DESCRIPTION
**Pull request by sdlime**
This should fix issue #5193. If OK, it should be applied to the 6.4 and 7.0 branches. --Steve

### CODE REVIEW

**Comment by sdlime** [comment]
@tbonfort, what is the preferred method to apply a pull request like this to older branches (7.0 and 6.4). Should I have prepared the pull request against 7.0 instead? --Steve

**Comment by tbonfort** [comment]
@sdlime it should ideally be based on 6.4. Don't bother too much, it can be easily back ported if not.

**Comment by tbonfort** [comment]
PS an autotest for this would be useful in the long run

**Comment by sdlime** [comment]
Any objection to the solution?

**Comment by tbonfort** [comment]
I can have a look if you need when I'm back from holiday next week. I'm not familiar with the expression parser so you probably know better than me anyways.

**Comment by sdlime** [comment]
I'll back port to the 7.0 and 6.4 branches by hand... --Steve

**Pull request merged**
