### PR TITLE
Add docstrings to all MapScript classes and methods

### PR DESCRIPTION
**Pull request by geographika**
This pull request adds Doxygen-style docstrings to all MapScript classes and methods. This is part of [MS RFC 132: Update MapScript API Docs](https://mapserver.org/development/rfc/ms-rfc-132.html). Changes in this pull request are limited to the SWIG *.i interface files. 
Documentation has been taken from https://mapserver.org/mapscript/mapscript.html where available. 
Other changes include:

- standardising header includes into mapscript.i (some were duplicated)
- tab/space formatting
- typos
- add missing method documentation where possible

I've not had enough time to investigate every undocumented function or TODO from the docs, but hopefully these will build up over time along with expanding the Python MapScript test suite. 

There remain the following tasks which will be added in separate pull requests:

- %feature("shadow")  in Python not yet added (docstrings currently being ignored for these)
- class properties to be documented in the mapserver.h file
- Sphinx doc updates to use the new autodoc approach

### CODE REVIEW

**Comment by sdlime** [comment]
This approach does look cleaner - less clutter in the files.

**Comment by geographika** [comment]
@sdlime - is it ok to merge this, and then update the header files with comments for all MapScript accessible properties (using standard C comments) in a separate pull request?

**Comment by geographika** [comment]
If there are no objections I'll merge this in the next couple of days.

**Comment by sdlime** [comment]
No objections from me. Merge away!

**Pull request merged**
