### PR TITLE
Add Proj and GDAL versions to MapServer version output

### PR DESCRIPTION
**Pull request by geographika**
This pull request adds the version numbers of PROJ and GDAL to the version output for MapServer (using `mapserv -v` on the command line, and also present in some error messages). Both are required dependencies (at least since 8.0) so will always have a value. 

As different versions of PROJ and GDAL can have an impact on how MapServer behaves, and what is supported, it is useful to be able to easily access this information, and allow users to report it when having problems. 

The output will now look similar to the following:

```
MapServer version 8.1-dev PROJ version 7.2 GDAL version 3.4 OUTPUT=PNG 
OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE
SUPPORTS=CAIRO SUPPORTS=SVG_SYMBOLS SUPPORTS=SVGCAIRO SUPPORTS=ICONV 
SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER
SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER
SUPPORTS=OGCAPI_SERVER SUPPORTS=FASTCGI SUPPORTS=THREADS
SUPPORTS=GEOS SUPPORTS=PBF INPUT=JPEG INPUT=POSTGIS
INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE INPUT=FLATGEOBUF
```

Note the additional text - `PROJ version 7.2 GDAL version 3.4`. 

For production environments it is recommended that the `MS_NO_VERSION` environment variable is set to avoid these details being displayed to client applications:

https://github.com/MapServer/MapServer/blob/9209de5962ffc5287ab2c52f597b58f1751e2e1d/etc/mapserver-sample.conf#L42-L43

### CODE REVIEW

**Comment by sdlime** [comment]
This information does show up in error messages though... Makes the MS_NO_VERSION config file option more important.

**Comment by geographika** [comment]
@sdlime - `mapserv -v` seems fine to me already?
We could simply remove the version from all client responses (and leave it in the command line apps). There are only 3 places - WFS, SOS, and WMS, and then the general `msCGIWriteError` where it would need to be removed. 
It is also available as a template `[version]` option which I think should be left. 

Alternatively maybe setting `MS_NO_VERSION` to 1 by default would work?

**Comment by sdlime** [comment]
@geographika, I was thinking about the web client responses specifically. Suppressing version from the places you reference would be the best fix IMHO. That would also remove the need for MS_NO_VERSION altogether.

Setting MS_NO_VERSION by default would mean pushing that key into the config before loading the config file. There's currently no mechanism to unset it. Currently the code just checks for the presence of the key and doesn't look at the value. That would need to change, so "1" or "TRUE" would turn it on and anything else would turn if off. I'm sort of thinking why bother and go with your first suggestion. 

Maybe a question for the -dev list?

**Comment by geographika** [comment]
I think we could set the default to off using:

```
if(CPLGetConfigOption("MS_NO_VERSION", 1) == 1) return "";
```

and then a user would have to explicitly set  `MS_NO_VERSION 0` in their config file. 

However, I'd be for removing all version details from error messages. Admins can always login to a server and call `mapserv -v` to get these details.

**Comment by rouault** [comment]
The backport of this to 8.0 broke PROJ < 6 support (cf #6905, fix in #6906), but we should be more prudent on what we backport. This is a new functionality, not a bugfix.

**Pull request merged**
